version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    build:
      context: ./besu
      dockerfile: ${BESU_DOCKERFILE}
      args:
        - BUILD_TARGET=${BESU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${BESU_DOCKER_TAG}
    image: besu:local
    user: besu
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - besu-eth1-data:/var/lib/besu
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HOST_IP}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - /opt/besu/bin/besu
      - --data-path
      - /var/lib/besu
      - --p2p-port
      - ${EL_P2P_PORT:-30303}
      - --rpc-http-enabled
      - --rpc-http-api
      - "WEB3,ETH,NET"
      - --rpc-http-host
      - 0.0.0.0
      - --rpc-http-port
      - ${EL_RPC_PORT:-8545}
      - --rpc-http-cors-origins=*
      - --rpc-http-max-active-connections=65536
      - --rpc-ws-enabled
      - --rpc-ws-api
      - "WEB3,ETH,NET"
      - --rpc-ws-host
      - 0.0.0.0
      - --rpc-ws-port
      - ${EL_WS_PORT:-8546}
      - --max-peers
      - ${EL_MAX_PEER_COUNT:-25}
      - --fast-sync-min-peers
      - ${EL_MIN_PEER_COUNT:-5}
      - --host-allowlist=*
      - --logging
      - ${LOG_LEVEL}
      - --network
      - ${EL_NETWORK:-goerli}
      - --metrics-enabled
      - --metrics-host
      - 0.0.0.0
      - --metrics-port
      - "6060"
      - --data-storage-format=BONSAI
      - --sync-mode=X_SNAP
  eth:
    depends_on:
      - execution
volumes:
  besu-eth1-data:
