version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    stop_grace_period: 5m
    build:
      context: ./besu
      dockerfile: ${BESU_DOCKERFILE}
      args:
        - BUILD_TARGET=${BESU_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${BESU_SRC_REPO:-https://github.com/hyperledger/besu}
        - DOCKER_TAG=${BESU_DOCKER_TAG:-latest}
        - DOCKER_REPO=${BESU_DOCKER_REPO:-hyperledger/besu}
    image: besu:local
    user: besu
    environment:
      - JAVA_OPTS=${BESU_HEAP:--Xmx5g}
      - JWT_SECRET=${JWT_SECRET:-}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
    volumes:
      - besu-eth1-data:/var/lib/besu
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/besu/ee-secret
    ports:
      - ${HOST_IP:-}${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /opt/besu/bin/besu
      - --data-path
      - /var/lib/besu
      - --p2p-port
      - ${EL_P2P_PORT:-30303}
      - --rpc-http-enabled
      - --rpc-http-host
      - 0.0.0.0
      - --rpc-http-port
      - ${EL_RPC_PORT:-8545}
      - --rpc-http-cors-origins=*
      - --rpc-http-max-active-connections=65536
      - --rpc-max-logs-range=65536
      - --rpc-ws-enabled
      - --rpc-ws-api
      - "WEB3,ETH,NET"
      - --rpc-ws-host
      - 0.0.0.0
      - --rpc-ws-port
      - ${EL_WS_PORT:-8546}
      - --max-peers
      - ${EL_MAX_PEER_COUNT:-25}
      - --host-allowlist=*
      - --engine-host-allowlist=*
      - --engine-jwt-secret=/var/lib/besu/ee-secret/jwtsecret
      - --engine-rpc-port=${EE_PORT:-8551}
      - --logging
      - ${LOG_LEVEL}
      - --metrics-enabled
      - --metrics-host
      - 0.0.0.0
      - --metrics-port
      - "6060"
      - --nat-method=DOCKER
    labels:
      - traefik.enable=true
      - traefik.http.routers.${EL_HOST:-el}.service=${EL_HOST:-el}
      - traefik.http.routers.${EL_HOST:-el}.entrypoints=websecure
      - traefik.http.routers.${EL_HOST:-el}.rule=Host(`${EL_HOST:-el}.${DOMAIN}`)
      - traefik.http.routers.${EL_HOST:-el}.tls.certresolver=letsencrypt
      - traefik.http.routers.${EL_HOST:-el}lb.service=${EL_HOST:-el}
      - traefik.http.routers.${EL_HOST:-el}lb.entrypoints=websecure
      - traefik.http.routers.${EL_HOST:-el}lb.rule=Host(`${EL_LB:-el-lb}.${DOMAIN}`)
      - traefik.http.routers.${EL_HOST:-el}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${EL_HOST:-el}.loadbalancer.server.port=${EL_RPC_PORT:-8545}
      - traefik.http.routers.${EL_WS_HOST:-elws}.service=${EL_WS_HOST:-elws}
      - traefik.http.routers.${EL_WS_HOST:-elws}.entrypoints=websecure
      - traefik.http.routers.${EL_WS_HOST:-elws}.rule=Host(`${EL_WS_HOST:-elws}.${DOMAIN}`)
      - traefik.http.routers.${EL_WS_HOST:-elws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.service=${EL_WS_HOST:-elws}
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.entrypoints=websecure
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.rule=Host(`${EL_WS_LB:-elws-lb}.${DOMAIN}`)
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${EL_WS_HOST:-elws}.loadbalancer.server.port=${EL_WS_PORT:-8546}
      - traefik.http.routers.${EE_HOST:-ee}.service=${EE_HOST:-ee}
      - traefik.http.routers.${EE_HOST:-ee}.entrypoints=websecure
      - traefik.http.routers.${EE_HOST:-ee}.rule=Host(`${EE_HOST:-ee}.${DOMAIN}`)
      - traefik.http.routers.${EE_HOST:-ee}.tls.certresolver=letsencrypt
      - traefik.http.services.${EE_HOST:-ee}.loadbalancer.server.port=${EE_PORT:-8551}
volumes:
  besu-eth1-data:
  jwtsecret:
