version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  ssv2-node:
    restart: "unless-stopped"
    image: bloxstaking/ssv-node-shifu:${SSV2_NODE_TAG:-v0.3.0-rc.1}
    user: 12000:12000
    volumes:
      - ./blox-ssv-config.yaml:/config.yaml
      - ssv2-data:/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${SSV_P2P_PORT}:${SSV_P2P_PORT}/tcp
      - ${SSV_P2P_PORT_UDP}:${SSV_P2P_PORT_UDP}/udp
    <<: *logging
    environment:
      - CONFIG_PATH=/config.yaml
      - HOME=/tmp
    command: make BUILD_PATH=/go/bin/ssvnode start-node
  ssv-generate-keys:
    profiles: ["tools"]
    restart: "no"
    image: bloxstaking/ssv-node-shifu:${SSV2_NODE_TAG:-v0.3.0-rc.1}
    command: /go/bin/ssvnode generate-operator-keys
volumes:
  ssv2-data:
