# For scraping with central-proxy-docker, when all you want is the metrics exporter
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  ethereum-metrics-exporter:
    restart: "unless-stopped"
    image: samcm/ethereum-metrics-exporter:0.23.0-debian
    entrypoint:
      - /ethereum-metrics-exporter
      - --consensus-url=${CL_NODE}
      - --execution-url=http://execution:${EL_RPC_PORT:-8545}
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=ethereum-metrics-exporter
      - metrics.network=${NETWORK}
