# For scraping with central-proxy-docker, when all you want is the metrics exporter
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  ethereum-metrics-exporter:
    restart: "unless-stopped"
    build:
      context: ./eth-metrics
    image: ethereum-metrics-exporter:local
    pull_policy: never
    environment:
      - CLIENT=${COMPOSE_FILE}
    entrypoint:
      - docker-entrypoint.sh
      - /ethereum-metrics-exporter
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=ethereum-metrics-exporter
    <<: *logging
