# To be used in conjunction with lodestar.yml, nimbus.yml, teku.yml, lighthouse.yml or prysm.yml, ditto their
# -cl-only.yml versions
# For remote validator setups only. Please be very cautious when exposing your consensus API port
services:
  consensus:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CL_HOST:-cl}.service=${CL_HOST:-cl}
      - traefik.http.routers.${CL_HOST:-cl}.entrypoints=websecure
      - traefik.http.routers.${CL_HOST:-cl}.rule=Host(`${CL_HOST:-cl}.${DOMAIN}`)
      - traefik.http.routers.${CL_HOST:-cl}.tls.certresolver=letsencrypt
      - traefik.http.routers.${CL_HOST:-cl}lb.service=${CL_HOST:-cl}
      - traefik.http.routers.${CL_HOST:-cl}lb.entrypoints=websecure
      - traefik.http.routers.${CL_HOST:-cl}lb.rule=Host(`${CL_LB:-cl-lb}.${DOMAIN}`)
      - traefik.http.routers.${CL_HOST:-cl}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${CL_HOST:-cl}.loadbalancer.server.port=${CL_REST_PORT:-5052}
