services:
  deposit-cli-new:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./ethstaker-deposit-cli
      dockerfile: ${DEPCLI_DOCKERFILE}
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${DEPCLI_SRC_REPO:-https://github.com/eth-educators/ethstaker-deposit-cli}
        - DOCKER_TAG=${DEPLCI_DOCKER_TAG:-latest}
        - DOCKER_REPO=${DEPLCI_DOCKER_REPO:-ghcr.io/eth-educators/ethstaker-deposit-cli}
    image: ethstaker-deposit-cli:local
    pull_policy: never
    volumes:
      - ./.eth:/app/.eth/
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - -m
      - ethstaker_deposit
      - new-mnemonic
      - --chain
      - ${NETWORK}
  deposit-cli-existing:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./ethstaker-deposit-cli
      dockerfile: ${DEPCLI_DOCKERFILE}
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${DEPCLI_SRC_REPO:-https://github.com/eth-educators/ethstaker-deposit-cli}
        - DOCKER_TAG=${DEPLCI_DOCKER_TAG:-latest}
        - DOCKER_REPO=${DEPLCI_DOCKER_REPO:-ghcr.io/eth-educators/ethstaker-deposit-cli}
    image: ethstaker-deposit-cli:local
    pull_policy: never
    volumes:
      - ./.eth:/app/.eth/
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - -m
      - ethstaker_deposit
      - existing-mnemonic
      - --chain
      - ${NETWORK}
  deposit-cli-change:
    profiles: ["tools"]
    build:
      context: ./ethstaker-deposit-cli
      dockerfile: ${DEPCLI_DOCKERFILE}
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${DEPCLI_SRC_REPO:-https://github.com/eth-educators/ethstaker-deposit-cli}
        - DOCKER_TAG=${DEPLCI_DOCKER_TAG:-latest}
        - DOCKER_REPO=${DEPLCI_DOCKER_REPO:-ghcr.io/eth-educators/ethstaker-deposit-cli}
    restart: "no"
    image: ethstaker-deposit-cli:local
    pull_policy: never
    volumes:
      - ./.eth:/app/.eth
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - -m
      - ethstaker_deposit
      - generate-bls-to-execution-change
      - --chain
      - ${NETWORK}
