version: "3.9"
services:
  deposit-cli-new:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./staking-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
    image: staking-deposit-cli:local
    volumes:
      - ./.eth:/app/.eth/
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - /app/staking_deposit/deposit.py
      - new-mnemonic
      - --chain
      - ${NETWORK}
  deposit-cli-existing:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./staking-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
    image: staking-deposit-cli:local
    volumes:
      - ./.eth:/app/.eth/
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - /app/staking_deposit/deposit.py
      - existing-mnemonic
      - --chain
      - ${NETWORK}
  deposit-cli-change:
    profiles: ["tools"]
    build:
      context: ./staking-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
    restart: "no"
    image: staking-deposit-cli:local
    volumes:
      - ./.eth:/app/.eth
    entrypoint:
      - docker-entrypoint.sh
      - python3
      - /app/staking_deposit/deposit.py
      - generate-bls-to-execution-change
      - --chain
      - ${NETWORK}
