# To be used in conjunction with oe.yml, nm.yml, besu.yml or geth.yml
version: "3.4"
services:
  execution:
    ports:
      - ${ETH1_RPC_PORT}${EC_RPC_PORT}:${ETH1_RPC_PORT}${EC_RPC_PORT}/tcp
      - ${ETH1_WS_PORT}${EC_WS_PORT}:${ETH1_WS_PORT}${EC_WS_PORT}/tcp
  eth:
    image: tianon/true
