version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  erigon:
    restart: "${RESTART}"
    build:
      context: ./erigon
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - BUILD_TARGET=${ERIGON_SRC_BUILD_TARGET}
        - DOCKER_TAG=${ERIGON_DOCKER_TAG}
    stop_grace_period: 5m
    image: erigon:local-merge
    user: erigon
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    expose:
      - 9090/tcp
      - 6060/tcp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - erigon
      - --private.api.addr
      - 0.0.0.0:9090
      - --datadir
      - /var/lib/erigon
      - --port
      - ${EL_P2P_PORT}
      - --nat
      - any
      - --prune=htc
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --metrics.expensive
      - --bootnodes
      - ${ENODE}
      - --networkid
      - ${NETWORK_ID}
  execution:
    restart: "${RESTART}"
    image: erigon:local-merge
    #    user: erigon
    user: root
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}-secrets:/secrets
    expose:
      - ${EL_RPC_PORT}/tcp
    depends_on:
      - erigon
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    entrypoint:
      - docker-entrypoint-rpc.sh
      - rpcdaemon
      - --datadir
      - /var/lib/erigon
      - --private.api.addr
      - erigon:9090
      - --txpool.api.addr
      - erigon:9090
      - --http.addr
      - 0.0.0.0
      - --engine.addr
      - 0.0.0.0
      - --authrpc.jwtsecret
      - /var/lib/erigon/jwtsecret
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api
      - web3,eth,net,engine
      - --http.port
      - ${EL_RPC_PORT}
      - --ws
  eth:
    depends_on:
      - execution
volumes:
  erigon-el-data:
