version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./erigon
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - BUILD_TARGET=${ERIGON_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${ERIGON_SRC_REPO:-https://github.com/ledgerwatch/erigon}
        - DOCKER_TAG=${ERIGON_DOCKER_TAG:-stable}
        - DOCKER_REPO=${ERIGON_DOCKER_REPO:-thorax/erigon}
    stop_grace_period: 5m
    image: erigon:local
    user: erigon
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/erigon/ee-secret
    ports:
      - ${HOST_IP:-}${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_2:-30304}:${ERIGON_P2P_PORT_2:-30304}/tcp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_2:-30304}:${ERIGON_P2P_PORT_2:-30304}/udp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_3:-30305}:${ERIGON_P2P_PORT_3:-30305}/tcp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_3:-30305}:${ERIGON_P2P_PORT_3:-30305}/udp
      # torrent ports
      - ${HOST_IP:-}${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/tcp
      - ${HOST_IP:-}${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - erigon
      - --private.api.addr
      - 0.0.0.0:9090
      - --datadir
      - /var/lib/erigon
      - --port
      - ${EL_P2P_PORT:-30303}
      - --p2p.allowed-ports
      - ${EL_P2P_PORT:-30303},${ERIGON_P2P_PORT_2:-30304},${ERIGON_P2P_PORT_3:-30305}
      - --torrent.port
      - ${ERIGON_TORRENT_PORT:-42069}
      - --nat
      - any
      - --log.console.verbosity
      - ${LOG_LEVEL}
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${EL_RPC_PORT}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      # Allow RocketPool >=1.9 watchtower queries
      - --rpc.returndata.limit
      - "1000000"
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret
      - /var/lib/erigon/ee-secret/jwtsecret
      - --maxpeers
      - ${EL_MAX_PEER_COUNT:-100}
      # To assist with recordsize 16k in ZFS
      - --db.pagesize
      - 16K
      # Memory use reduction. Not needed with 32G and does not help with 16G
      #- --batchSize
      #- 64m
    labels:
      - traefik.enable=true
      - traefik.http.routers.${EL_HOST:-el}.service=${EL_HOST:-el}
      - traefik.http.routers.${EL_HOST:-el}.entrypoints=websecure
      - traefik.http.routers.${EL_HOST:-el}.rule=Host(`${EL_HOST:-el}.${DOMAIN}`)
      - traefik.http.routers.${EL_HOST:-el}.tls.certresolver=letsencrypt
      - traefik.http.routers.${EL_HOST:-el}lb.service=${EL_HOST:-el}
      - traefik.http.routers.${EL_HOST:-el}lb.entrypoints=websecure
      - traefik.http.routers.${EL_HOST:-el}lb.rule=Host(`${EL_LB:-el-lb}.${DOMAIN}`)
      - traefik.http.routers.${EL_HOST:-el}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${EL_HOST:-el}.loadbalancer.server.port=${EL_RPC_PORT:-8545}
      - traefik.http.routers.${EL_WS_HOST:-elws}.service=${EL_WS_HOST:-elws}
      - traefik.http.routers.${EL_WS_HOST:-elws}.entrypoints=websecure
      - traefik.http.routers.${EL_WS_HOST:-elws}.rule=Host(`${EL_WS_HOST:-elws}.${DOMAIN}`)
      - traefik.http.routers.${EL_WS_HOST:-elws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.service=${EL_WS_HOST:-elws}
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.entrypoints=websecure
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.rule=Host(`${EL_WS_LB:-elws-lb}.${DOMAIN}`)
      - traefik.http.routers.${EL_WS_HOST:-elws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${EL_WS_HOST:-elws}.loadbalancer.server.port=${EL_WS_PORT:-8546}
      - traefik.http.routers.${EE_HOST:-ee}.service=${EE_HOST:-ee}
      - traefik.http.routers.${EE_HOST:-ee}.entrypoints=websecure
      - traefik.http.routers.${EE_HOST:-ee}.rule=Host(`${EE_HOST:-ee}.${DOMAIN}`)
      - traefik.http.routers.${EE_HOST:-ee}.tls.certresolver=letsencrypt
      - traefik.http.services.${EE_HOST:-ee}.loadbalancer.server.port=${EE_PORT:-8551}
volumes:
  erigon-el-data:
  jwtsecret:
