version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./erigon
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - BUILD_TARGET=${ERIGON_SRC_BUILD_TARGET}
        - DOCKER_TAG=${ERIGON_DOCKER_TAG}
    stop_grace_period: 5m
    image: erigon:local
    user: erigon
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/erigon/ee-secret
    ports:
      - ${HOST_IP:-}${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_2:-30304}:${ERIGON_P2P_PORT_2:-30304}/tcp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_2:-30304}:${ERIGON_P2P_PORT_2:-30304}/udp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_3:-30305}:${ERIGON_P2P_PORT_3:-30305}/tcp
      - ${HOST_IP:-}${ERIGON_P2P_PORT_3:-30305}:${ERIGON_P2P_PORT_3:-30305}/udp
      # torrent ports
      - ${HOST_IP:-}${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/tcp
      - ${HOST_IP:-}${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - erigon
      - --private.api.addr
      - 0.0.0.0:9090
      - --datadir
      - /var/lib/erigon
      - --port
      - ${EL_P2P_PORT:-30303}
      - --p2p.allowed-ports
      - ${EL_P2P_PORT:-30303},${ERIGON_P2P_PORT_2:-30304},${ERIGON_P2P_PORT_3:-30305}
      - --torrent.port
      - ${ERIGON_TORRENT_PORT:-42069}
      - --nat
      - any
      - --chain
      - ${NETWORK}
      - --log.console.verbosity
      - ${LOG_LEVEL}
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${EL_RPC_PORT}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api
      - web3,eth,net,engine
      - --ws
      # Allow RocketPool >=1.9 watchtower queries
      - --rpc.returndata.limit
      - "1000000"
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret
      - /var/lib/erigon/ee-secret/jwtsecret
      - --maxpeers
      - ${EL_MAX_PEER_COUNT:-100}
      # To assist with recordsize 16k in ZFS
      - --db.pagesize
      - 16K
      # Memory use reduction. Not needed with 32G and does not help with 16G
      #- --batchSize
      #- 64m
volumes:
  erigon-el-data:
  jwtsecret:
