x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./erigon
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - BUILD_TARGET=${ERIGON_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${ERIGON_SRC_REPO:-https://github.com/ledgerwatch/erigon}
        - DOCKER_TAG=${ERIGON_DOCKER_TAG:-latest}
        - DOCKER_REPO=${ERIGON_DOCKER_REPO:-erigontech/erigon}
    stop_grace_period: 5m
    image: erigon:local
    pull_policy: never
    user: erigon
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${EL_ARCHIVE_NODE:-}
      - EL_MINIMAL_NODE=${EL_MINIMAL_NODE:-}
      - NETWORK=${NETWORK}
      - IPV6=${IPV6:-false}
      - DOCKER_TAG=${ERIGON_DOCKER_TAG:-latest}
      - COMPOSE_FILE=${COMPOSE_FILE}
      - CL_P2P_PORT=${CL_P2P_PORT:-9000}
      - CL_REST_PORT=${CL_REST_PORT:-5052}
      - CHECKPOINT_SYNC_URL=${CHECKPOINT_SYNC_URL:-}
      - MEV_BOOST=${MEV_BOOST:-false}
      - MEV_NODE=${MEV_NODE:-}
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/erigon/ee-secret
    ports:
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
      - ${HOST_IP:-}:${EL_P2P_PORT_2:-30304}:${EL_P2P_PORT_2:-30304}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT_2:-30304}:${EL_P2P_PORT_2:-30304}/udp
      - ${HOST_IP:-}:${ERIGON_P2P_PORT_3:-30305}:${ERIGON_P2P_PORT_3:-30305}/tcp
      - ${HOST_IP:-}:${ERIGON_P2P_PORT_3:-30305}:${ERIGON_P2P_PORT_3:-30305}/udp
      # torrent ports
      - ${HOST_IP:-}:${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/tcp
      - ${HOST_IP:-}:${ERIGON_TORRENT_PORT:-42069}:${ERIGON_TORRENT_PORT:-42069}/udp
    networks:
      default:
        aliases:
          - eth1
          - ${EL_ALIAS:-default-execution}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - erigon
      - --private.api.addr
      - 0.0.0.0:9090
      - --datadir
      - /var/lib/erigon
      - --port
      - ${EL_P2P_PORT:-30303}
      - --p2p.allowed-ports
      - ${EL_P2P_PORT:-30303},${EL_P2P_PORT_2:-30304},${ERIGON_P2P_PORT_3:-30305}
      - --torrent.port
      - ${ERIGON_TORRENT_PORT:-42069}
      - --nat
      - any
      - --log.console.verbosity
      - ${LOG_LEVEL}
      - --metrics
      - --metrics.addr
      - 0.0.0.0
# Erigon needs this to be explicit. When it's covered by defaults, remove
      - --http.api
      - web3,eth,net,engine
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${EL_RPC_PORT}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      # Allow RocketPool >=1.9 watchtower queries
      - --rpc.returndata.limit
      - "1000000"
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret
      - /var/lib/erigon/ee-secret/jwtsecret
      - --maxpeers
      - ${EL_MAX_PEER_COUNT:-100}
    labels:
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
      - metrics.instance=execution
      - metrics.network=${NETWORK}

  wipe-db:
    profiles: ["tools"]
    restart: "no"
    image: alpine:3
    user: "10001"
    volumes:
      - erigon-el-data:/var/lib/erigon
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        rm -rf /var/lib/erigon/caplin/*

volumes:
  erigon-el-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
