# To be used with one of the yml files that start a CL client
services:
  ethdo:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./ethdo
    image: ethdo:local
    pull_policy: never
    volumes:
      - ./.eth:/app/.eth
      - ethdo-wallet:/app/wallet
    environment:
      - NETWORK=${NETWORK}
      - CL_NODE=${CL_NODE:-http://consensus:5052}
    entrypoint:
      - docker-entrypoint.sh
      - /app/ethdo
      - --allow-insecure-connections

volumes:
  ethdo-wallet:
