# To be used with one of the yml files that start a CL client
version: "3.9"
services:
  ethdo:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./ethdo
    image: ethdo:local
    volumes:
      - ./.eth:/app/.eth
    environment:
      - NETWORK=${NETWORK}
    entrypoint:
      - docker-entrypoint.sh
      - /app/ethdo
      -  --connection
      - http://consensus:5052
      - --allow-insecure-connections
    depends_on:
      - consensus
