x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  portal:
    restart: "unless-stopped"
    build:
      context: ./fluffy
      dockerfile: ${FLUFFY_DOCKERFILE}
      args:
        - BUILD_TARGET=${FLUFFY_SRC_BUILD_TARGET:-master}
        - SRC_REPO=${FLUFFY_SRC_REPO:-https://github.com/status-im/nimbus-eth1}
        - DOCKER_TAG=${FLUFFY_DOCKER_TAG:-amd64-master-latest}
        - DOCKER_REPO=${FLUFFY_DOCKER_REPO:-statusim/nimbus-fluffy}
    stop_grace_period: 5m
    stop_signal: SIGINT
    image: fluffy:local
    pull_policy: never
    user: user
    volumes:
      - nimbus-fluffy-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HOST_IP:-}:${PORTAL_P2P_PORT:-9009}:${PORTAL_P2P_PORT:-9009}/udp
    networks:
      default:
        aliases:
          - ${PORTAL_ALIAS:-default-portal}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - fluffy
      - --data-dir=/var/lib/nimbus
      - --network=${NETWORK}
      - --rpc
      - --rpc-address=0.0.0.0
      - --rpc-port=${PORTAL_RPC_PORT:-8545}
      - --ws
      - --ws-address=0.0.0.0
      - --ws-port=${PORTAL_WS_PORT:-8546}
      - --udp-port=${PORTAL_P2P_PORT:-9009}
      - --enr-auto-update
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --log-level=${LOG_LEVEL}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=portal
      - metrics.network=${NETWORK}

volumes:
  nimbus-fluffy-data:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
