version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  execution:
    restart: "${RESTART}"
    build:
      context: ./geth
      dockerfile: ${GETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${GETH_DOCKER_TAG}
    stop_grace_period: 3m
    image: geth:local
    user: geth
    volumes:
      - geth-eth1-data:/var/lib/goethereum
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${EC_P2P_PORT}:${EC_P2P_PORT}/tcp
      - ${EC_P2P_PORT}:${EC_P2P_PORT}/udp
    expose:
      - ${EC_RPC_PORT}/tcp
      - ${EC_WS_PORT}/tcp
      - 6060/tcp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - geth
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api
      - web3,eth,net
      - --datadir
      - /var/lib/goethereum
      - --port
      - ${EC_P2P_PORT}
      - --http.port
      - ${EC_RPC_PORT}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EC_WS_PORT}
      - --ws.api
      - web3,eth,net
      - --${EC_NETWORK}
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
    command: ${GETH_CACHE}
  eth:
    depends_on:
      - execution
volumes:
  geth-eth1-data:
