x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./geth
      dockerfile: ${GETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${GETH_SRC_REPO:-https://github.com/ethereum/go-ethereum}
        - DOCKER_TAG=${GETH_DOCKER_TAG:-stable}
        - DOCKER_REPO=${GETH_DOCKER_REPO:-ethereum/client-go}
    stop_grace_period: 5m
    image: geth:local
    pull_policy: never
    user: geth
    environment:
      - JWT_SECRET=${JWT_SECRET:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
      - IPV6=${IPV6:-false}
      - ANCIENT_DIR=${ANCIENT_DIR:-}
    volumes:
      - geth-eth1-data:/var/lib/goethereum
      - ${ANCIENT_DIR:-.nada}:/var/lib/ancient
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/goethereum/ee-secret
    ports:
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
          - ${NETWORK}-execution # This allows multiple Eth Docker stacks all connected to the same central traefik
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --datadir
      - /var/lib/goethereum
      - --port
      - ${EL_P2P_PORT:-30303}
      - --http.port
      - ${EL_RPC_PORT:-8545}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EL_WS_PORT:-8546}
      - --ws.origins=*
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
      - --authrpc.jwtsecret
      - /var/lib/goethereum/ee-secret/jwtsecret
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.vhosts=*
      - --maxpeers
      - ${EL_MAX_PEER_COUNT:-50}
    labels:
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
      - metrics.instance=execution

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10001:10001"
    restart: "no"
    volumes:
      - geth-eth1-data:/var/lib/goethereum
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  geth-eth1-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
