# Grafana for use with rootless docker. Omits node-exporter, cadvisor, promtail and Loki
version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  prometheus:
    restart: "unless-stopped"
    build:
      context: ./prometheus
    image: prometheus:local
    volumes:
      - prom-data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CLIENT=${COMPOSE_FILE}
    entrypoint: choose-config.sh
    command: ["/bin/prometheus", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles"]
    <<: *logging
    depends_on:
      - blackbox-exporter
      - json-exporter
      - cryptowat-exporter
      - ethereum-metrics-exporter

  ethereum-metrics-exporter:
    restart: "unless-stopped"
    build:
      context: ./eth-metrics
    image: ethereum-metrics-exporter:local
    environment:
      - CLIENT=${COMPOSE_FILE}
    entrypoint:
      - docker-entrypoint.sh
      - /ethereum-metrics-exporter
    <<: *logging

  blackbox-exporter:
    restart: "unless-stopped"
    image: prom/blackbox-exporter:master
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --config.file=/config/blackbox.yml

  json-exporter:
    restart: "unless-stopped"
    image: quay.io/prometheuscommunity/json-exporter
    volumes:
      - ./prometheus/json.yml:/config/json.yml
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --config.file
      - /config/json.yml

  cryptowat-exporter:
    restart: "unless-stopped"
    image: nbarrientos/cryptowat_exporter
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CRYPTOWAT_EXCHANGES=kraken
      - CRYPTOWAT_PAIRS=ethusd,ethchf
      - CRYPTOWAT_CACHESECONDS=300
      - TZ=Europe/Zurich
    <<: *logging

  grafana:
    restart: "unless-stopped"
    build:
      context: ./grafana
    image: grafana:local
    # Defaults to root user. The script adjusts permissions and switches to grafana user since 12/26/2022
    # This can be changed after a must-have update has been deployed by most (all?) users - possibly late 2023.
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
      - CLIENT=${COMPOSE_FILE}
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus
    entrypoint: ["provision-dashboards.sh"]
    command: /run.sh
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web,websecure
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}.${DOMAIN}`)
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=${GRAFANA_PORT}

volumes:
  grafana-data:
  grafana-config:
  prom-data:
