x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'


x-build: &gr-build
  context: ./grandine
  dockerfile: ${GRANDINE_DOCKERFILE:-Dockerfile.binary}
  args:
    - BUILD_TARGET=${GRANDINE_SRC_BUILD_TARGET:-master}
    - SRC_REPO=${GRANDINE_SRC_REPO:-https://github.com/sifraitech/grandine}
    - DOCKER_TAG=${GRANDINE_DOCKER_TAG:-latest}
    - DOCKER_REPO=${GRANDINE_DOCKER_REPO:-sifrai/grandine}

services:
  consensus:
    restart: "unless-stopped"
    build:
      <<: *gr-build
    image: grandine:local
    pull_policy: never
    user: gdconsensus
    stop_grace_period: 1m
    volumes:
      - grandineconsensus-data:/var/lib/grandine
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/grandine/ee-secret
    environment:
      - CHECKPOINT_SYNC_URL=${CHECKPOINT_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - EMBEDDED_VC=false
      - VC_EXTRAS=
      - WEB3SIGNER=false
      - DOPPELGANGER=false
      - GRAFFITI=
      - DEFAULT_GRAFFITI=true
      - ARCHIVE_NODE=${CL_ARCHIVE_NODE:-false}
      - CL_MINIMAL_NODE=${CL_MINIMAL_NODE:-true}
      - IPV6=${IPV6:-false}
      - CL_P2P_PORT=${CL_P2P_PORT:-9000}
      - CL_QUIC_PORT=${CL_QUIC_PORT:-9001}
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
      - ${HOST_IP:-}:${CL_QUIC_PORT:-9001}:${CL_QUIC_PORT:-9001}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${CL_ALIAS:-default-consensus}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - grandine
      - --disable-upnp
      - --data-dir
      - /var/lib/grandine
      - --http-address
      - 0.0.0.0
      - --http-port
      - ${CL_REST_PORT:-5052}
      - --http-allowed-origins=*
      - --listen-address
      - 0.0.0.0
      - --libp2p-port
      - ${CL_P2P_PORT:-9000}
      - --discovery-port
      - ${CL_P2P_PORT:-9000}
      - --quic-port
      - ${CL_QUIC_PORT:-9001}
      - --target-peers
      - ${CL_MAX_PEER_COUNT:-80}
      - --eth1-rpc-urls
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/grandine/ee-secret/jwtsecret
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --metrics-port
      - "8008"
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus
      - metrics.network=${NETWORK}

  wipe-db:
    profiles: ["tools"]
    restart: "no"
    image: alpine:3
    user: "10002"
    volumes:
      - grandineconsensus-data:/var/lib/grandine
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        rm -rf /var/lib/grandine/${NETWORK}/beacon/*

volumes:
  grandineconsensus-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
