version: "3.4"
services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./lighthouse
      dockerfile: ${LH_DOCKERFILE}
      args:
        - BUILD_TARGET=${LH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LH_DOCKER_TAG}
    image: lighthouse:local
    stop_grace_period: 1m
    volumes:
      - /data/eth/${NETWORK}/beacon:/var/lib/lighthouse
      # - lhbeacon-data:/var/lib/lighthouse
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${LH_PORT}:${LH_PORT}/tcp
      - ${LH_PORT}:${LH_PORT}/udp
      - 5054:5054
    expose:
      - 5052/tcp
      - 5054/tcp
    entrypoint: 
      - docker-entrypoint.sh
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - 0.0.0.0
      - --http-port
      - '5052'
      - --network
      - ${NETWORK}
      - --port
      - ${LH_PORT}
      - --target-peers
      - ${LH_PEER_COUNT}
      - --eth1-endpoints
      - ${ETH1_NODE}${EC_NODE}
      - --eth1-blocks-per-log-query
      - "150"
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --metrics-port
      - '5054'
      - --validator-monitor-auto
  validator:
    restart: "${RESTART}"
    image: lighthouse:local
    volumes:
      - /data/eth/${NETWORK}/validator:/var/lib/lighthouse
      # - lhvalidator-data:/var/lib/lighthouse
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - docker-entrypoint.sh
      - lighthouse
      - vc
      - --datadir
      - /var/lib/lighthouse
      - --beacon-nodes
      - ${BN_NODE}${CC_NODE}
      - --graffiti
      - ${GRAFFITI}
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
    depends_on:
      - consensus
  validator-import:
    restart: "no"
    image: lighthouse:local
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator-import.sh
      - lighthouse
      - account
      - validator
      - import
      - --datadir
      - /var/lib/lighthouse
      - --directory
      - /val_keys
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
  validator-exit:
    restart: "no"
    image: lighthouse:local
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator-exit.sh
      - lighthouse
      - account
      - validator
      - exit
      - --beacon-node
      - http://consensus:5052
      - --datadir
      - /var/lib/lighthouse
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
      - --keystore
    depends_on:
      - consensus
  validator-account:
    restart: "no"
    image: lighthouse:local
    user: lhvalidator
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}:/interchange
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - lighthouse
      - account
      - validator
      - --datadir
      - /var/lib/lighthouse
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
      - validator
volumes:
  lhbeacon-data:
  lhvalidator-data:
