x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  charon:
    restart: "unless-stopped"
    image: obolnetwork/charon:${CHARON_VERSION:-latest}
    volumes:
      - .eth:/opt/charon/.charon
    <<: *logging
    environment:
      - CHARON_BEACON_NODE_ENDPOINTS=${OBOL_CHARON_CL_ENDPOINTS:-http://consensus:5052}
      - CHARON_LOG_LEVEL=${OBOL_LOG_LEVEL:-debug}
      - CHARON_LOG_FORMAT=${OBOL_LOG_FORMAT:-console}
      - CHARON_P2P_RELAYS=${OBOL_P2P_RELAYS:-https://0.relay.obol.tech,https://1.relay.obol.tech/}
      - CHARON_P2P_EXTERNAL_HOSTNAME=${OBOL_P2P_EXTERNAL_HOSTNAME:-} # Empty default required to avoid warnings.
      - CHARON_P2P_TCP_ADDRESS=0.0.0.0:${OBOL_P2P_PORT:-3610}
      - CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600
      - CHARON_MONITORING_ADDRESS=0.0.0.0:3620
      - CHARON_BUILDER_API=${BUILDER_API_ENABLED:-true}
      - CHARON_FEATURE_SET_ENABLE=eager_double_linear,consensus_participate
      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-http://loki:3100/loki/api/v1/push}
      - CHARON_LOKI_SERVICE=charon
    ports:
      - ${OBOL_P2P_PORT:-3610}:${OBOL_P2P_PORT:-3610}/tcp # P2P TCP libp2p
    healthcheck:
      test: wget -qO- http://localhost:3620/readyz
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3620
      - metrics.instance=charon

  charon-create-enr:
    profiles: ["tools"]
    restart: "no"
    image: obolnetwork/charon:${CHARON_VERSION:-latest}
    command: create enr
    volumes:
      - .eth:/opt/charon/.charon
  charon-run-dkg:
    profiles: ["tools"]
    restart: "no"
    image: obolnetwork/charon:${CHARON_VERSION:-latest}
    volumes:
      - .eth:/opt/charon/.charon
    command: dkg --publish
  curl-jq:
    image: curl-jq:local
    pull_policy: build
    build:
      context: ./traefik
      dockerfile: Dockerfile.jq
    restart: "no"
    profiles: [ "tools" ]

  validator-ejector:
   platform: linux/amd64
   image: lidofinance/validator-ejector:${VALIDATOR_EJECTOR_VERSION:-1.5.0}
   user: ":"
   volumes:
     - .eth/lido-ejector:/exitmessages
   restart: unless-stopped
   environment:
     -  EXECUTION_NODE=${OBOL_EL_NODE:-http://execution:8545}
     -  CONSENSUS_NODE=${OBOL_CL_NODE:-http://consensus:5052}
     -  LOCATOR_ADDRESS=${VE_LOCATOR_ADDRESS:-0x28FAB2059C713A7F9D8c86Db49f9bb0e96Af1ef8}
     -  STAKING_MODULE_ID=${VE_STAKING_MODULE_ID:-2}
     -  OPERATOR_ID=${VE_OPERATOR_ID}
     -  ORACLE_ADDRESSES_ALLOWLIST=${VE_ORACLE_ADDRESSES_ALLOWLIST:-["0x140Bd8FbDc884f48dA7cb1c09bE8A2fAdfea776E","0xA7410857ABbf75043d61ea54e07D57A6EB6EF186","0x404335BcE530400a5814375E7Ec1FB55fAff3eA2","0x946D3b081ed19173dC83Cd974fC69e1e760B7d78","0x007DE4a5F7bc37E2F26c0cb2E8A95006EE9B89b5","0xe57B3792aDCc5da47EF4fF588883F0ee0c9835C9","0x61c91ECd902EB56e314bB2D5c5C07785444Ea1c8","0x73181107c8D9ED4ce0bbeF7A0b4ccf3320C41d12","0xc79F702202E3A6B0B6310B537E786B9ACAA19BAf"]}
     -  MESSAGES_LOCATION=/exitmessages
     -  RUN_METRICS=true
     -  HTTP_PORT=8989
     -  DISABLE_SECURITY_DONT_USE_IN_PRODUCTION=${VE_DISABLE_SECURITY:-false}
     -  FORCE_DENCUN_FORK_MODE=true
   labels:
     - metrics.scrape=true
     - metrics.path=/metrics
     - metrics.port=8989
     - metrics.instance=validator-ejector

  lido-dv-exit:
    image: obolnetwork/lido-dv-exit:${LIDO_DV_EXIT_VERSION:-c4c00c3}
    user: ":"
    volumes:
      - .eth/lido-ejector:/exitmessages
      - .eth:/charon
    environment:
      - LIDODVEXIT_BEACON_NODE_URL=${OBOL_CL_NODE:-http://consensus:5052}
      - LIDODVEXIT_CHARON_RUNTIME_DIR=/charon
      - LIDODVEXIT_EJECTOR_EXIT_PATH=/exitmessages
      - LIDODVEXIT_EXIT_EPOCH=${LIDO_DV_EXIT_EXIT_EPOCH:-194048}
      - LIDODVEXIT_LOG_LEVEL=${LIDO_DV_EXIT_LOG_LEVEL:-info}
      - LIDODVEXIT_VALIDATOR_QUERY_CHUNK_SIZE=${LIDO_DV_EXIT_VALIDATOR_QUERY_CHUNK_SIZE:-5}
    restart: unless-stopped

networks:
  default:
    enable_ipv6: ${IPV6:-false}
