version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &lh-build
  context: ./lighthouse
  dockerfile: ${LH_DOCKERFILE}
  args:
    - BUILD_TARGET=${LH_SRC_BUILD_TARGET:-stable}
    - SRC_REPO=${LH_SRC_REPO:-https://github.com/sigp/lighthouse}
    - DOCKER_TAG=${LH_DOCKER_TAG:-latest-modern}
    - DOCKER_REPO=${LH_DOCKER_REPO:-sigp/lighthouse}

services:
  consensus:
    restart: "unless-stopped"
    build:
      <<: *lh-build
    image: lighthouse:local
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lighthouse/beacon/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-false}
      - IPV6=${IPV6:-false}
      - CL_P2P_PORT=${CL_P2P_PORT:-9000}
      - CL_QUIC_PORT=${CL_QUIC_PORT:-9001}
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
      - ${HOST_IP:-}${CL_QUIC_PORT:-9001}:${CL_QUIC_PORT:-9001}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${NETWORK}-consensus
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --gui
      - --http-address
      - 0.0.0.0
      - --http-port
      - ${CL_REST_PORT:-5052}
      - --port
      - ${CL_P2P_PORT:-9000}
      - --quic-port
      - ${CL_QUIC_PORT:-9001}
      - --target-peers
      - ${CL_MAX_PEER_COUNT:-100}
      - --execution-endpoint
      - ${EL_NODE}
      - --execution-jwt
      - /var/lib/lighthouse/beacon/ee-secret/jwtsecret
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --metrics-port
      - "8008"
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus

  set-cl-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10002:10002"
    restart: "no"
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  lhconsensus-data:
  jwtsecret:
