version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'


x-build: &lh-build
  context: ./lighthouse
  dockerfile: ${LH_DOCKERFILE}
  args:
    - BUILD_TARGET=${LH_SRC_BUILD_TARGET}
    - DOCKER_TAG=${LH_DOCKER_TAG}

services:
  consensus:
    restart: "unless-stopped"
    build:
      <<: *lh-build
    image: lighthouse:local
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lhbeacon-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lighthouse/beacon/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
    ports:
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - 0.0.0.0
      - --http-port
      - ${CL_REST_PORT:-5052}
      - --network
      - ${NETWORK}
      - --listen-address
      - 0.0.0.0
      - --listen-address
      - "::"
      - --port
      - ${CL_P2P_PORT:-9000}
      - --port6
      - ${CL_P2P_PORT:-9000}
      - --target-peers
      - ${CL_MAX_PEER_COUNT:-80}
      - --execution-endpoint
      - ${EL_NODE}
      - --execution-jwt
      - /var/lib/lighthouse/beacon/ee-secret/jwtsecret
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --metrics-port
      - "8008"
      - --validator-monitor-auto
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}

  validator:
    restart: "unless-stopped"
    build:
      <<: *lh-build
    image: lighthouse:local
    user: lhvalidator
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - DOPPELGANGER=${DOPPELGANGER}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - lighthouse
      - vc
      - --datadir
      - /var/lib/lighthouse
      - --beacon-nodes
      - ${CL_NODE:-http://consensus:5052}
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --metrics-port
      - "8009"
      - --http
      - --http-port
      - ${KEY_API_PORT:-7500}
      - --http-address
      - 0.0.0.0
      - --http-allow-origin=*
      - --unencrypted-http-transport
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
    depends_on:
      - consensus

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    build:
      <<: *lh-build
    image: lighthouse:local
    # Keys have 440 permissions. Root copies and chowns them,
    # then switches to user lhvalidator
    user: root
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator-exit.sh
      - lighthouse
      - account
      - validator
      - exit
      - --beacon-node
      - http://consensus:5052
      - --datadir
      - /var/lib/lighthouse
      - --network
      - ${NETWORK}
      - --debug-level=${LOG_LEVEL}
      - --keystore
    depends_on:
      - consensus

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    # The API token has 640 permissions. Root copies it,
    # then switches to the local user's UID or if not provided,
    # 1000. The UID has to be able to write .eth/validator_keys
    # for the "keys delete" command.
    user: root
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/lighthouse/validators/api-token.txt
      - validator

volumes:
  lhbeacon-data:
  lhvalidator-data:
  jwtsecret:
