x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &ls-build
  context: ./lodestar
  dockerfile: ${LS_DOCKERFILE}
  args:
    - BUILD_TARGET=${LS_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
    - SRC_REPO=${LS_SRC_REPO:-https://github.com/ChainSafe/lodestar}
    - DOCKER_TAG=${LS_DOCKER_TAG:-latest}
    - DOCKER_REPO=${LS_DOCKER_REPO:-chainsafe/lodestar}

services:
  consensus:
    restart: "unless-stopped"
    build:
      <<: *ls-build
    image: lodestar:local
    pull_policy: never
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lodestar/consensus/ee-secret
    environment:
      - CHECKPOINT_SYNC_URL=${CHECKPOINT_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${CL_ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
      - IPV6=${IPV6:-false}
      - CL_IPV6_P2P_PORT=${CL_IPV6_P2P_PORT:-9090}
      - NODE_OPTIONS=${LODESTAR_HEAP:---max-old-space-size=8192}
    ports:
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
      - ${HOST_IP:-}:${CL_IPV6_P2P_PORT:-9090}:${CL_IPV6_P2P_PORT:-9090}/tcp
      - ${HOST_IP:-}:${CL_IPV6_P2P_PORT:-9090}:${CL_IPV6_P2P_PORT:-9090}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${CL_ALIAS:-default-consensus}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --dataDir
      - /var/lib/lodestar/consensus
      - --rest.address
      - 0.0.0.0
      - --rest.port
      - ${CL_REST_PORT:-5052}
      - --port
      - ${CL_P2P_PORT:-9000}
      - --nat
      - --metrics
      - "true"
      - --metrics.port
      - "8008"
      - --metrics.address
      - 0.0.0.0
      - --execution.urls
      - ${EL_NODE}
      - --jwtSecret
      - /var/lib/lodestar/consensus/ee-secret/jwtsecret
      - --targetPeers
      - ${CL_MAX_PEER_COUNT:-100}
      - --logLevel
      - ${LOG_LEVEL}
      - --suggestedFeeRecipient
      - ${FEE_RECIPIENT}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus
      - metrics.network=${NETWORK}

volumes:
  lsconsensus-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
