version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &ls-build
  context: ./lodestar
  dockerfile: ${LS_DOCKERFILE}
  args:
    - BUILD_TARGET=${LS_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
    - SRC_REPO=${LS_SRC_REPO:-https://github.com/ChainSafe/lodestar}
    - DOCKER_TAG=${LS_DOCKER_TAG:-latest}
    - DOCKER_REPO=${LS_DOCKER_REPO:-chainsafe/lodestar}

services:
  consensus:
    restart: "unless-stopped"
    build:
      <<: *ls-build
    image: lodestar:local
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lodestar/consensus/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
      - NODE_OPTIONS=${LODESTAR_HEAP:---max-old-space-size=4096}
    ports:
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --dataDir
      - /var/lib/lodestar/consensus
      - --rest.address
      - 0.0.0.0
      - --rest.port
      - ${CL_REST_PORT:-5052}
      - --rest.namespace
      - "beacon,config,events,node,validator,lightclient,debug"
      - --port
      - ${CL_P2P_PORT:-9000}
      - --nat
      - --metrics
      - "true"
      - --metrics.port
      - "8008"
      - --metrics.address
      - 0.0.0.0
      - --execution.urls
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/lodestar/consensus/ee-secret/jwtsecret
      - --targetPeers
      - ${CL_MAX_PEER_COUNT:-50}
      - --logLevel
      - ${LOG_LEVEL}
      - --suggestedFeeRecipient
      - ${FEE_RECIPIENT}

  validator:
    restart: "unless-stopped"
    build:
      <<: *ls-build
    image: lodestar:local
    user: lsvalidator
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - DOPPELGANGER=${DOPPELGANGER}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
      - WEB3SIGNER=${WEB3SIGNER}
      - NETWORK=${NETWORK}
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - consensus
    networks:
      default:
        aliases:
          - vc
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - node
      - --max-old-space-size=2048
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - --dataDir
      - /var/lib/lodestar/validators
      - --beaconNodes
      - ${CL_NODE}
      - --keymanager
      - --keymanager.address
      - 0.0.0.0
      - --keymanager.port
      - ${KEY_API_PORT:-7500}
      - --metrics
      - "true"
      - --metrics.port
      - "8009"
      - --metrics.address
      - 0.0.0.0
      - --logLevel
      - ${LOG_LEVEL}
      - --suggestedFeeRecipient
      - ${FEE_RECIPIENT}
      - --force

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    build:
      <<: *ls-build
    image: lodestar:local
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=2048
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - voluntary-exit
      - --dataDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      -  --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}
      - --force

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - ./.eth/exit_messages:/exit_messages
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
      - WEB3SIGNER=${WEB3SIGNER:-false}
      - CL_NODE=${CL_NODE}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/lodestar/validators/validator-db/api-token.txt
      - vc

volumes:
  lsconsensus-data:
  lsvalidator-data:
  jwtsecret:
