version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./lodestar
      dockerfile: ${LS_DOCKERFILE}
      args:
        - BUILD_TARGET=${LS_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LS_DOCKER_TAG}
    image: lodestar:local
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
    ports:
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --rootDir
      - /var/lib/lodestar/consensus
      - --api.rest.enabled
      - "true"
      - --api.rest.host
      - 0.0.0.0
      - --api.rest.port
      - "5052"
      - --network.discv5.bindAddr
      - "/ip4/0.0.0.0/udp/${CL_P2P_PORT:-9000}"
      - --network.localMultiaddrs
      - "/ip4/0.0.0.0/tcp/${CL_P2P_PORT:-9000}"
      - --network.maxPeers
      - ${CL_MAX_PEER_COUNT:-55}
      - --network.targetPeers
      - ${CL_MIN_PEER_COUNT:-50}
      - --eth1.providerUrls
      - ${EL_NODE:-http://execution:8545}
      - --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}
  validator:
    restart: "${RESTART}"
    image: lodestar:local
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      - --graffiti
      - ${GRAFFITI}
      - --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}
  validator-import:
    restart: "${RESTART}"
    image: lodestar:local
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - NETWORK=${NETWORK}
    entrypoint:
      - validator-import.sh
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - import
      - --rootDir
      - /var/lib/lodestar/validators
      - --directory
      - /val_keys
      - --network
      - ${NETWORK}
    depends_on:
      - consensus
  validator-exit:
    restart: "no"
    image: lodestar:local
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - account
      - validator
      - voluntary-exit
      - --rootDir
      - /var/lib/lodestar/validators
      - --server
      - http://consensus:5052
      -  --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}
  validator-account:
    restart: "no"
    image: lodestar:local
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - account
      - validator
      - --rootDir
      - /var/lib/lodestar/validators
      - --network
      - ${NETWORK}
  validator-list:
    restart: "no"
    image: lodestar:local
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=6144
      - /usr/app/node_modules/.bin/lodestar
      - account
      - validator
      - list
      - --rootDir
      - /var/lib/lodestar/validators
      - --network
      - ${NETWORK}
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
      - validator
volumes:
  lsconsensus-data:
  lsvalidator-data:
