version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: "unless-stopped"
    image: lodestar:local
    user: lsvalidator
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - DOPPELGANGER=${DOPPELGANGER}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - --dataDir
      - /var/lib/lodestar/validators
      - --beaconNodes
      - ${CL_NODE:-http://consensus:5052}
      - --keymanager
      - --keymanager.address
      - 0.0.0.0
      - --keymanager.port
      - ${KEY_API_PORT:-7500}
      - --metrics
      - "true"
      - --metrics.port
      - "8009"
      - --metrics.address
      - 0.0.0.0
      - --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}
      - --suggestedFeeRecipient
      - ${FEE_RECIPIENT}

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: lodestar:local
    user: lsvalidator
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - validator
      - voluntary-exit
      - --dataDir
      - /var/lib/lodestar/validators
      - --server
      - ${CL_NODE:-http://consensus:5052}
      -  --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - lsvalidator-data:/var/lib/lodestar/validators
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/lodestar/validators/validator-db/api-token.txt
      - validator

volumes:
  lsvalidator-data:
