version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "unless-stopped"
    build:
      context: ./lodestar
      dockerfile: ${LS_DOCKERFILE}
      args:
        - BUILD_TARGET=${LS_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LS_DOCKER_TAG}
    image: lodestar:local
    user: lsconsensus
    stop_grace_period: 1m
    volumes:
      - lsconsensus-data:/var/lib/lodestar/consensus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/lodestar/consensus/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
    ports:
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - --max-old-space-size=4096
      - /usr/app/node_modules/.bin/lodestar
      - beacon
      - --dataDir
      - /var/lib/lodestar/consensus
      - --rest.address
      - 0.0.0.0
      - --rest.port
      - ${CL_REST_PORT:-5052}
      - --port
      - ${CL_P2P_PORT:-9000}
      - --metrics
      - "true"
      - --metrics.port
      - "8008"
      - --metrics.address
      - 0.0.0.0
      - --execution.urls
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/lodestar/consensus/ee-secret/jwtsecret
      - --targetPeers
      - ${CL_MIN_PEER_COUNT:-50}
      - --logLevel
      - ${LOG_LEVEL}
      - --network
      - ${NETWORK}
      - --suggestedFeeRecipient
      - ${FEE_RECIPIENT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CL_HOST:-cl}.service=${CL_HOST:-cl}
      - traefik.http.routers.${CL_HOST:-cl}.entrypoints=websecure
      - traefik.http.routers.${CL_HOST:-cl}.rule=Host(`${CL_HOST:-cl}.${DOMAIN}`)
      - traefik.http.routers.${CL_HOST:-cl}.tls.certresolver=letsencrypt
      - traefik.http.routers.${CL_HOST:-cl}lb.service=${CL_HOST:-cl}
      - traefik.http.routers.${CL_HOST:-cl}lb.entrypoints=websecure
      - traefik.http.routers.${CL_HOST:-cl}lb.rule=Host(`${CL_LB:-cl-lb}.${DOMAIN}`)
      - traefik.http.routers.${CL_HOST:-cl}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${CL_HOST:-cl}.loadbalancer.server.port=${CL_REST_PORT:-5052}
volumes:
  lsconsensus-data:
  jwtsecret:
