version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local
    user: user
    stop_grace_period: 1m
    volumes:
      - nimbus-data:/var/lib/nimbus
      - .eth/keymanagertoken:/keymanagertoken
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8008/tcp
    ports:
      - ${CC_P2P_PORT:-9000}:${CC_P2P_PORT:-9000}/tcp
      - ${CC_P2P_PORT:-9000}:${CC_P2P_PORT:-9000}/udp
      - 127.0.0.1:6052:6052/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --status-bar=false
      - --tcp-port=${CC_P2P_PORT:-9000}
      - --udp-port=${CC_P2P_PORT:-9000}
      - --max-peers=${NIM_PEER_COUNT}
      - --network=${NETWORK}
      - --web3-url=${EC_NODE}
      - --web3-url=${EC_FALLBACK_NODE1}
      - --web3-url=${EC_FALLBACK_NODE2}
      - --graffiti=${GRAFFITI}
      - --log-level=${LOG_LEVEL}
      - --rpc
      - --rpc-address=0.0.0.0
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5052
      - --num-threads=0
      - --enr-auto-update=true
      - --doppelganger-detection=false
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --validator-monitor-auto
      - --keymanager
      - --keymanager-port=6052
      - --keymanager-address=0.0.0.0
      - --keymanager-token-file=/var/lib/nimbus/token
    command: ${NIMBUS_RAPID_SYNC}
  validator-import:
    restart: "no"
    image: nimbus:local
    user: root
    volumes:
      - nimbus-data:/var/lib/nimbus
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-''}
    entrypoint:
      - validator-import.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --network=${NETWORK}
      - deposits
      - import
      - /val_keys
  validator-exit:
    restart: "no"
    image: nimbus:local
    user: user
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --network=${NETWORK}
      - --log-level=${LOG_LEVEL}
      - deposits
      - exit
      - --rpc-url=http://consensus:9190
      - --validator=
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  nimbus-data:
