version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: "unless-stopped"
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local
    user: vc-user
    volumes:
      - nimbus-vc-data:/var/lib/nimbus-vc
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nimbus/ee-secret
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - DOPPELGANGER=${DOPPELGANGER}
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - /usr/local/bin/nimbus_validator_client
      - --data-dir=/var/lib/nimbus-vc
      - --non-interactive
      - --beacon-node=${CL_NODE}
      - --graffiti=${GRAFFITI}
      - --log-level=${LOG_LEVEL}
      - --metrics
      - --metrics-port=8009
      - --metrics-address=0.0.0.0
      - --keymanager
      - --keymanager-port=${KEY_API_PORT:-7500}
      - --keymanager-address=0.0.0.0
      - --keymanager-allow-origin=*
      - --keymanager-token-file=/var/lib/nimbus-vc/api-token.txt
      - --suggested-fee-recipient=${FEE_RECIPIENT}
    command: ${VC_EXTRAS}

  validator-import:
    profiles: ["tools"]
    restart: "no"
    image: nimbus:local
    user: root
    volumes:
      - nimbus-vc-data:/var/lib/nimbus-vc
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - NETWORK=${NETWORK}
    entrypoint:
      - validator-import.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus-vc
      - --network=${NETWORK}
      - deposits
      - import
      - /val_keys

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: nimbus:local
    user: vc-user
    volumes:
      - nimbus-vc-data:/var/lib/nimbus-vc
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus-vc
      - --network=${NETWORK}
      - --log-level=${LOG_LEVEL}
      - deposits
      - exit
      - --rest-url=http://consensus:5052
      - --validator=

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - nimbus-vc-data:/var/lib/nimbus-vc
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/nimbus-vc/api-token.txt
      - validator

volumes:
  nimbus-vc-data:
  jwtsecret:
