x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./nimbus-el
      dockerfile: ${NIMEL_DOCKERFILE}
      args:
        - BUILD_TARGET=${NIMEL_SRC_BUILD_TARGET:-master}
        - SRC_REPO=${NIMEL_SRC_REPO:-https://github.com/status-im/nimbus-eth1}
        - DOCKER_TAG=${NIMEL_DOCKER_TAG:-master}
        - DOCKER_REPO=${NIMEL_DOCKER_REPO:-statusim/nimbus-eth1}
    stop_grace_period: 5m
    stop_signal: SIGINT
    image: nimbus-el:local
    pull_policy: never
    user: user
    environment:
      - JWT_SECRET=${JWT_SECRET:-}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${EL_ARCHIVE_NODE:-false}
      - MINIMAL_NODE=${EL_MINIMAL_NODE:-false}
      - NETWORK=${NETWORK}
      - ERA1_URL=${ERA1_URL:-}
      - ERA_URL=${ERA_URL:-}
      - PORTAL_NODE=${PORTAL_NODE}
      - PORTAL=${PORTAL:-false}
    volumes:
      - nimbus-el-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nimbus/ee-secret
    ports:
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
          - ${EL_ALIAS:-default-execution}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - nimbus_execution_client
      - --rpc
      - --http-address=0.0.0.0
      - --http-port=${EL_RPC_PORT:-8545}
      - --ws
      - --data-dir=/var/lib/nimbus
      - --tcp-port=${EL_P2P_PORT:-30303}
      - --discovery=V5
      - --metrics
      - --metrics-port=6060
      - --metrics-address=0.0.0.0
      - --jwt-secret=/var/lib/nimbus/ee-secret/jwtsecret
      - --engine-api
      - --engine-api-port=${EE_PORT:-8551}
      - --engine-api-address=0.0.0.0
      - --engine-api-ws
      - --max-peers=${EL_MAX_PEER_COUNT:-25}
      - --log-level=${LOG_LEVEL}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=6060
      - metrics.instance=execution
      - metrics.network=${NETWORK}

volumes:
  nimbus-el-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
