version: "3"
services:
  beacon:
    expose:
      - 8008/tcp
    command:
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
  prometheus:
    restart: "no"
    build:
      context: ./prometheus
    image: prometheus
    volumes:
      - prom-data:/prometheus
    environment:
      - CLIENT=${COMPOSE_FILE}
    expose:
      - 9090/tcp
    entrypoint: choose-config.sh
    command: ["/bin/prometheus", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles"]
    depends_on:
      - beacon
      - node-exporter
  node-exporter:
    restart: "no"
    image: prom/node-exporter
    expose:
      - 9100/tcp
  grafana:
    restart: "no"
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    ports: 
      - ${GRAFANA_PORT}:3000/tcp
  eth2:
    depends_on:
      - grafana
volumes:
  grafana-data:
  prom-data:
