version: "3.4"
services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local
    stop_grace_period: 1m
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${NIM_PORT}:${NIM_PORT}/tcp
      - ${NIM_PORT}:${NIM_PORT}/udp
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --tcp-port=${NIM_PORT}
      - --udp-port=${NIM_PORT}
      - --max-peers=${NIM_PEER_COUNT}
      - --network=${NETWORK}
      - --web3-url=${ETH1_NODE}${EC_NODE}
      - --graffiti=${GRAFFITI}
      - --log-level=${LOG_LEVEL}
      - --rpc
      - --rpc-address=0.0.0.0
      - --enr-auto-update=true
  validator-import:
    restart: "no"
    image: nimbus:local
    volumes:
      - nimbus-data:/var/lib/nimbus
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator-import.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --network=${NETWORK}
      - deposits
      - import
      - /val_keys
  validator-exit:
    restart: "no"
    user: user
    image: nimbus:local
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --network=${NETWORK}
      - --log-level=${LOG_LEVEL}
      - deposits
      - exit
      - --rpc-url=http://consensus:9190
      - --validator=
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  nimbus-data:
