version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &nimbus-build
  context: ./nimbus
  dockerfile: ${NIM_DOCKERFILE}
  args:
    - BUILD_TARGET=${NIM_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
    - SRC_REPO=${NIM_SRC_REPO:-https://github.com/status-im/nimbus-eth2}
    - DOCKER_TAG=${NIM_DOCKER_TAG:-multiarch-latest}
    - DOCKER_VC_TAG=${NIM_DOCKER_VC_TAG:-multiarch-latest}
    - DOCKER_REPO=${NIM_DOCKER_REPO:-statusim/nimbus-eth2}
    - DOCKER_VC_REPO=${NIM_DOCKER_VC_REPO:-statusim/nimbus-validator-client}

services:
  consensus:
    restart: "unless-stopped"
    build:
      target: consensus
      <<: *nimbus-build
    image: nimbus:local
    user: user
    stop_grace_period: 1m
    volumes:
      - nimbus-consensus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nimbus/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - NETWORK=${NETWORK}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - DOPPELGANGER=false
      - CL_EXTRAS=${CL_EXTRAS:-}
      - VC_EXTRAS=
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=true
      - WEB3SIGNER=false
      - EMBEDDED_VC=false
    ports:
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${NETWORK}-consensus
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --status-bar=false
      - --tcp-port=${CL_P2P_PORT:-9000}
      - --udp-port=${CL_P2P_PORT:-9000}
      - --max-peers=${CL_MAX_PEER_COUNT:-160}
      - --el=${EL_NODE}
      - --jwt-secret=/var/lib/nimbus/ee-secret/jwtsecret
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=${CL_REST_PORT:-5052}
      - --enr-auto-update=true
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --in-process-validators=false
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus

  validator:
    restart: "unless-stopped"
    build:
      target: validator
      <<: *nimbus-build
    image: nimbus-validator:local
    user: user
    volumes:
      - nimbus-vc-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nimbus/ee-secret
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - DOPPELGANGER=${DOPPELGANGER}
      - LOG_LEVEL=${LOG_LEVEL}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
      - WEB3SIGNER=${WEB3SIGNER:-false}
    networks:
      default:
        aliases:
          - vc
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - /usr/local/bin/nimbus_validator_client
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --beacon-node=${CL_NODE}
      - --metrics
      - --metrics-port=8009
      - --metrics-address=0.0.0.0
      - --keymanager
      - --keymanager-port=${KEY_API_PORT:-7500}
      - --keymanager-address=0.0.0.0
      - --keymanager-allow-origin=*
      - --keymanager-token-file=/var/lib/nimbus/api-token.txt
      - --suggested-fee-recipient=${FEE_RECIPIENT}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8009
      - metrics.instance=validator

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: alpine:3
    entrypoint:
      - /bin/sh
      - -c
      - echo "Legacy exit not supported with Nimbus validator client. Please use ./ethd keys sign-exit instead, then submit to beaconcha.in or use ./ethd keys send-exit"

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - nimbus-vc-data:/var/lib/nimbus
      - ./.eth/validator_keys:/validator_keys
      - ./.eth/exit_messages:/exit_messages
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
      - WEB3SIGNER=${WEB3SIGNER:-false}
      - CL_NODE=${CL_NODE}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/nimbus/api-token.txt
      - vc

volumes:
  nimbus-consensus-data:
  nimbus-vc-data:
  jwtsecret:
