version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local-merge
    user: user
    stop_grace_period: 1m
    volumes:
      - nimbus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    expose:
      - 8008/tcp
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --status-bar=false
      - --tcp-port=${CL_P2P_PORT}
      - --udp-port=${CL_P2P_PORT}
      - --max-peers=${NIM_PEER_COUNT}
      - --web3-url=${EL_NODE}
      - --log-level=${LOG_LEVEL}
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5052
      - --enr-auto-update=true
      - --num-threads=0
      - --doppelganger-detection=false
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --validator-monitor-totals
      - --network=/configs
      - --bootstrap-node=${ENR}
      - --terminal-total-difficulty-override=${TOTAL_TERMINAL_DIFFICULTY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cl.service=cl
      - traefik.http.routers.cl.entrypoints=websecure
      - traefik.http.routers.cl.rule=Host(`${CL_HOST}.${DOMAIN}`)
      - traefik.http.routers.cl.tls.certresolver=letsencrypt
      - traefik.http.services.cl.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  nimbus-data:
