version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "unless-stopped"
    build:
      target: consensus
      context: ./nimbus
      args:
        - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NIM_DOCKER_TAG}
        - DOCKER_VC_TAG=${NIM_DOCKER_VC_TAG}
      dockerfile: ${NIM_DOCKERFILE}
    image: nimbus:local
    user: user
    stop_grace_period: 1m
    volumes:
      - nimbus-consensus-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nimbus/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - NETWORK=${NETWORK}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - DOPPELGANGER=false
      - CL_EXTRAS=${CL_EXTRAS:-}
      - VC_EXTRAS=
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=true
    ports:
      - ${HOST_IP:-0.0.0.0}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-0.0.0.0}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /usr/local/bin/nimbus_beacon_node
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --status-bar=false
      - --tcp-port=${CL_P2P_PORT:-9000}
      - --udp-port=${CL_P2P_PORT:-9000}
      - --max-peers=${CL_MAX_PEER_COUNT:-160}
      - --network=${NETWORK}
      - --web3-url=${EL_NODE}
      - --jwt-secret=/var/lib/nimbus/ee-secret/jwtsecret
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=${CL_REST_PORT:-5052}
      - --enr-auto-update=true
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --validator-monitor-totals
      - --keymanager
      - --keymanager-port=${KEY_API_PORT:-7500}
      - --keymanager-address=0.0.0.0
      - --keymanager-allow-origin=*
      - --keymanager-token-file=/var/lib/nimbus/api-token.txt
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --in-process-validators=false
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CL_HOST:-cl}.service=${CL_HOST:-cl}
      - traefik.http.routers.${CL_HOST:-cl}.entrypoints=websecure
      - traefik.http.routers.${CL_HOST:-cl}.rule=Host(`${CL_HOST:-cl}.${DOMAIN}`)
      - traefik.http.routers.${CL_HOST:-cl}.tls.certresolver=letsencrypt
      - traefik.http.routers.${CL_HOST:-cl}lb.service=${CL_HOST:-cl}
      - traefik.http.routers.${CL_HOST:-cl}lb.entrypoints=websecure
      - traefik.http.routers.${CL_HOST:-cl}lb.rule=Host(`${CL_LB:-cl-lb}.${DOMAIN}`)
      - traefik.http.routers.${CL_HOST:-cl}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${CL_HOST:-cl}.loadbalancer.server.port=${CL_REST_PORT:-5052}
volumes:
  nimbus-consensus-data:
  jwtsecret:
