version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &nimbus-build
  context: ./nimbus
  dockerfile: ${NIM_DOCKERFILE}
  args:
    - BUILD_TARGET=${NIM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${NIM_DOCKER_TAG}
    - DOCKER_VC_TAG=${NIM_DOCKER_VC_TAG}

services:
  validator:
    restart: "unless-stopped"
    build:
      target: validator
      <<: *nimbus-build
    image: nimbus-validator:local
    user: user
    volumes:
      - nimbus-vc-data:/var/lib/nimbus
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/nimbus/ee-secret
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - DOPPELGANGER=${DOPPELGANGER}
      - LOG_LEVEL=${LOG_LEVEL}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - /usr/local/bin/nimbus_validator_client
      - --data-dir=/var/lib/nimbus
      - --non-interactive
      - --beacon-node=${CL_NODE}
      - --metrics
      - --metrics-port=8009
      - --metrics-address=0.0.0.0
      - --keymanager
      - --keymanager-port=${KEY_API_PORT:-7500}
      - --keymanager-address=0.0.0.0
      - --keymanager-allow-origin=*
      - --keymanager-token-file=/var/lib/nimbus/api-token.txt
      - --suggested-fee-recipient=${FEE_RECIPIENT}

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - nimbus-vc-data:/var/lib/nimbus
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/nimbus/api-token.txt
      - validator

volumes:
  nimbus-vc-data:
  jwtsecret:
