version: "3.4"
services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    build:
      context: ./nethermind
      dockerfile: ${NM_DOCKERFILE}
      args:
        - BUILD_TARGET=${NM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NM_DOCKER_TAG}
    image: nethermind:local
    volumes:
      - nm-eth1-data:/var/lib/nethermind
    ports:
      - ${EC_P2P_PORT}:${EC_P2P_PORT}/tcp
      - ${EC_P2P_PORT}:${EC_P2P_PORT}/udp
    expose:
      - ${EC_RPC_PORT}/tcp
      - ${EC_WS_PORT}/tcp
    entrypoint:
      - docker-entrypoint.sh
      - dotnet
      - /nethermind/Nethermind.Runner.dll
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --Network.DiscoveryPort
      - ${EC_P2P_PORT}
      - --Network.P2PPort
      - ${EC_P2P_PORT}
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net"
      - --JsonRpc.Host
      - 0.0.0.0
      - --JsonRpc.Port
      - ${EC_RPC_PORT}
      - --JsonRpc.WebSocketsPort
      - ${EC_WS_PORT}
      - --Sync.FastSync
      - "true"
      - --config
      - ${EC_NETWORK}
      - --Pruning.Enabled
      - "true"
      - --Pruning.CacheMb
      - "4096"
  eth:
    depends_on:
      - execution
volumes:
  nm-eth1-data:
