version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}

services:
  validator:
    restart: "${RESTART}"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:local
    user: prysmvalidator
    ports:
      - 127.0.0.1:5062:5062
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - --beacon-rpc-provider
      - ${CC_NODE}
      - --graffiti
      - ${GRAFFITI}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --tls-cert
      - /etc/ssl/certs/ca-certificates.crt
      - --accept-terms-of-use
      # If you chose not to store the wallet password during import, comment out the two following lines
      - --wallet-password-file
      - /var/lib/prysm/password.txt
      - --rpc
      - --rpc-host
      - 0.0.0.0
      - --rpc-port
      - "5062"
  create-wallet:
    restart: "no"
    image: prysm-validator:local
    user: prysmvalidator
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint: create-wallet.sh
  get-keyapi-token:
    restart: "no"
    image: alpine:latest
    user: "10000"
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cat /var/lib/prysm/auth-token
  validator-list:
    restart: "no"
    image: prysm-validator:local
    user: prysmvalidator
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --verbosity
      - ${LOG_LEVEL}
      - accounts
      - list
      - --wallet-dir=/var/lib/prysm/
      - --${NETWORK}
      # If you chose not to store the wallet password during import, comment out the following line
      - --wallet-password-file=/var/lib/prysm/password.txt
  validator-import:
    restart: "no"
    image: prysm-validator:local
    user: root
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-''}
      - WALLET_PASSWORD=${WALLET_PASSWORD:-''}
    entrypoint:
      - validator-import.sh
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - import
      - --wallet-dir=/var/lib/prysm/
      - --keys-dir=/val_keys
      - --${NETWORK}
  validator-exit:
    restart: "no"
    image: prysm-validator:local
    user: prysmvalidator
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - voluntary-exit
      - --wallet-dir=/var/lib/prysm/
      - --beacon-rpc-provider=${CC_NODE}
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --${NETWORK}
      - --tls-cert=/etc/ssl/certs/ca-certificates.crt
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - validator
volumes:
  prysmvalidator-data:
