version: "3.4"
x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - USER=${PRYSM_USER}
    - UID=${LOCAL_UID}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}

services:
  beacon:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      target: beacon
      <<: *prysm-build
    image: prysm-beacon
    volumes:
      - prysmbeacon-data:/var/lib/prysm
    ports:
      - ${PRYSM_PORT}:${PRYSM_PORT}/tcp
      - ${PRYSM_UDP_PORT}:${PRYSM_UDP_PORT}/udp
    expose:
      - 4000
    entrypoint:
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --http-web3provider
      - ${ETH1_NODE}
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
  validator:
    restart: "${RESTART}"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator
    volumes:
      - prysmvalidator-data:/var/lib/prysm
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - --beacon-rpc-provider
      - beacon:4000
      - --graffiti
      - ${GRAFFITI}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
      # If you chose not to store the wallet password during import, comment out the two following lines
      - --wallet-password-file
      - /var/lib/prysm/password.txt
    depends_on:
      - beacon
  validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: prysm-validator
    build:
      target: validator
      <<: *prysm-build
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/prysm/validator_keys
    entrypoint: create-prysm-validator-wallet.sh
    command:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - import
      - --wallet-dir
      - /var/lib/prysm/
      - --keys-dir
      - /var/lib/prysm/validator_keys
      - --${NETWORK}
  validator-voluntary-exit:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: prysm-validator
    build:
      target: validator
      <<: *prysm-build
    volumes:
      - prysmvalidator-data:/var/lib/prysm
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - voluntary-exit
      - --wallet-dir
      - /var/lib/prysm/
      - --beacon-rpc-provider
      - beacon:4000
      - --wallet-password-file
      - /var/lib/prysm/password.txt
      - --${NETWORK}
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint:
      - python3
      - /app/eth2deposit/deposit.py
      - new-mnemonic
      - --folder
      - /var/lib/depcli-data
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${NETWORK}
  deposit-cli-add-recover:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_SRC_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint:
      - python3
      - /app/eth2deposit/deposit.py
      - existing-mnemonic
      - --folder
      - /var/lib/depcli-data
      - --num_validators
      - ${NUMVAL}
      - --validator_start_index
      - ${VAL_START_INDEX}
      - --chain
      - ${NETWORK}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
      - validator
volumes:
  prysmbeacon-data:
  prysmvalidator-data:
