x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
    - SRC_REPO=${PRYSM_SRC_REPO:-https://github.com/prysmaticlabs/prysm}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG:-stable}
    - DOCKER_VC_TAG=${PRYSM_DOCKER_VC_TAG:-stable}
    - DOCKER_REPO=${PRYSM_DOCKER_REPO:-gcr.io/prysmaticlabs/prysm/beacon-chain}
    - DOCKER_VC_REPO=${PRYSM_DOCKER_VC_REPO:-gcr.io/prysmaticlabs/prysm/validator}

services:
  consensus:
    restart: "unless-stopped"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:local
    pull_policy: never
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmbeacon-data:/var/lib/prysm-og
      - prysmconsensus-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/prysm/ee-secret
    environment:
      - CHECKPOINT_SYNC_URL=${CHECKPOINT_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${CL_ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}:${PRYSM_PORT}:${PRYSM_PORT}/tcp
      - ${HOST_IP:-}:${PRYSM_UDP_PORT}:${PRYSM_UDP_PORT}/udp
      - ${HOST_IP:-}:${CL_QUIC_PORT:-9001}:${CL_QUIC_PORT:-9001}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${CL_ALIAS:-default-consensus}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --http-host
      - 0.0.0.0
      - --http-port
      - ${CL_REST_PORT:-5052}
      - --http-cors-domain=*
      # Allow larger messages so credential change messages can be sent
      - --rpc-max-page-size
      - "200000"
      - --grpc-max-msg-size
      - "268435456"
      - --execution-endpoint
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/prysm/ee-secret/jwtsecret
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --p2p-quic-port
      - ${CL_QUIC_PORT}
      - --p2p-max-peers
      - ${CL_MAX_PEER_COUNT:-70}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --monitoring-port
      - "8008"
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus
      - metrics.network=${NETWORK}

  validator:
    restart: "unless-stopped"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:local
    pull_policy: never
    user: prysmvalidator
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MEV_BOOST=${MEV_BOOST}
      - DOPPELGANGER=${DOPPELGANGER}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
      - WEB3SIGNER=${WEB3SIGNER:-false}
      - W3S_NODE=${W3S_NODE}
      - NETWORK=${NETWORK}
      - ENABLE_DIST_ATTESTATION_AGGR=${ENABLE_DIST_ATTESTATION_AGGR:-false}
    networks:
      default:
        aliases:
          - ${VC_ALIAS:-vc}
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - --keymanager-token-file
      - /var/lib/prysm/auth-token
      - --beacon-rpc-provider
      - consensus:4000
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --monitoring-port
      - "8009"
      - --web
      - --http-host
      - 0.0.0.0
      - --http-port
      - ${KEY_API_PORT:-7500}
      - --http-cors-domain=*
      - --beacon-rest-api-provider
      - consensus:5052
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
      - --wallet-password-file
      - /var/lib/prysm/password.txt
    depends_on:
      - consensus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prysm.entrypoints=web,websecure
      - traefik.http.routers.prysm.rule=Host(`${PRYSM_HOST}.${DOMAIN}`)
      - traefik.http.routers.prysm.tls.certresolver=letsencrypt
      - traefik.http.services.prysm.loadbalancer.server.port=${KEY_API_PORT:-7500}
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8009
      - metrics.instance=validator
      - metrics.network=${NETWORK}

  create-wallet:
    profiles: ["tools"]
    restart: "no"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:local
    pull_policy: never
    user: prysmvalidator
    environment:
      - NETWORK=${NETWORK}
      - WEB3SIGNER=${WEB3SIGNER:-false}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint: create-wallet.sh

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: ${PRYSM_DOCKER_CTL_REPO}:${PRYSM_DOCKER_CTL_TAG}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /app/cmd/prysmctl/prysmctl
      - validator
      - exit
      - --wallet-dir=/var/lib/prysm/
      - --beacon-rpc-provider=consensus:4000
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --${NETWORK}
    depends_on:
      - consensus

  validator-backup:
    profiles: ["tools"]
    restart: "no"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:local
    pull_policy: never
    user: root
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - backup
      - --wallet-dir=/var/lib/prysm/
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --${NETWORK}
      - --backup-dir=/validator_keys
      - --backup-password-file=/var/lib/prysm/password.txt
    depends_on:
      - consensus

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    pull_policy: never
    user: root
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ./.eth/validator_keys:/validator_keys
      - ./.eth/exit_messages:/exit_messages
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
      - WEB3SIGNER=${WEB3SIGNER:-false}
      - W3S_NODE=${W3S_NODE}
      - CL_NODE=${CL_NODE}
      - PRYSM=true
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/prysm/auth-token
      - ${VC_ALIAS:-vc}

volumes:
  prysmbeacon-data:
  prysmconsensus-data:
  prysmvalidator-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
