version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}

services:
  consensus:
    restart: "${RESTART}"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:local
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmconsensus-data:/var/lib/prysm
      - certs:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080/tcp
    ports:
      - ${PRYSM_PORT}:${PRYSM_PORT}/tcp
      - ${PRYSM_UDP_PORT}:${PRYSM_UDP_PORT}/udp
    expose:
      - 5052/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - "5052"
      - --http-web3provider
      - ${EC_NODE}
      - --fallback-web3provider
      - ${EC_FALLBACK_NODE1}
      - --fallback-web3provider
      - ${EC_FALLBACK_NODE2}
      - --eth1-header-req-limit
      - "150"
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --p2p-max-peers
      - ${PRYSM_PEER_COUNT}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
      - --tls-cert
      - /letsencrypt/certs/certs/${DOMAIN}.crt
      - --tls-key
      - /letsencrypt/certs/private/${DOMAIN}.key
      - --monitoring-host
      - 0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.cc.entrypoints=websecure
      - traefik.http.routers.cc.rule=Host(`${CC_HOST}.${DOMAIN}`)
      - traefik.http.routers.cc.service=cc
      - traefik.http.routers.cc.tls.certresolver=letsencrypt
      - traefik.http.routers.cclb.service=cc
      - traefik.http.routers.cclb.entrypoints=websecure
      - traefik.http.routers.cclb.rule=Host(`${CC_LB}.${DOMAIN}`)
      - traefik.http.routers.cclb.tls.certresolver=letsencrypt
      - traefik.http.services.cc.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  prysmconsensus-data:
