version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG}

services:
  consensus:
    restart: "${RESTART}"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:local
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmconsensus-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    expose:
      - 5052/tcp
      - 4000/tcp
      - 8080/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - "5052"
      - --http-web3provider
      - ${EL_NODE}
      - --p2p-tcp-port
      - ${CL_P2P_PORT}
      - --p2p-udp-port
      - ${CL_P2P_PORT}
      - --p2p-max-peers
      - ${PRYSM_PEER_COUNT}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --genesis-state
      - /configs/genesis.ssz
      - --chain-config-file
      - /configs/config.yaml
      - --bootstrap-node
      - ${ENR}
      - --min-sync-peers=1
  validator:
    restart: "${RESTART}"
    build:
      target: validator
      <<: *prysm-build
    image: prysm-validator:local
    #user: prysmvalidator
    user: root
    expose:
      - 8081/tcp
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
      - ./${NETWORK}-secrets/keys/prysm:/keys
      - ./${NETWORK}-secrets/keys/secrets:/secrets
    <<: *logging
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /keys
      - --wallet-password-file
      - /secrets/prysm-password.txt
      - --beacon-rpc-provider
      - consensus:4000
      - --graffiti
      - ${GRAFFITI}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --web
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - ${PRYSM_WEB_PORT}
      - --chain-config-file
      - /configs/config.yaml
    depends_on:
      - consensus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prysm.service=prysm
      - traefik.http.routers.prysm.entrypoints=web,websecure
      - traefik.http.routers.prysm.rule=Host(`${PRYSM_HOST}.${DOMAIN}`)
      - traefik.http.routers.prysm.tls.certresolver=letsencrypt
      - traefik.http.services.prysm.loadbalancer.server.port=${PRYSM_WEB_PORT}
  validator-account-list:
    restart: "no"
    user: prysmvalidator
    image: prysm-validator:local
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --datadir
      - /var/lib/prysm
      - --verbosity
      - ${LOG_LEVEL}
      - accounts
      - list
      - --wallet-dir=/var/lib/prysm/
      - --wallet-password-file=/var/lib/prysm/password.txt
  validator-exit:
    restart: "no"
    user: prysmvalidator
    image: prysm-validator:local
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - validator
      - --verbosity
      - ${LOG_LEVEL}
      - --datadir
      - /var/lib/prysm
      - accounts
      - voluntary-exit
      - --wallet-dir=/var/lib/prysm/
      - --beacon-rpc-provider=consensus:4000
      - --wallet-password-file=/var/lib/prysm/password.txt
      - --kintsugi-testnet
    depends_on:
      - consensus
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
      - validator
volumes:
  prysmconsensus-data:
  prysmvalidator-data:
