version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &prysm-build
  context: ./prysm
  dockerfile: ${PRYSM_DOCKERFILE}
  args:
    - BUILD_TARGET=${PRYSM_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
    - SRC_REPO=${PRYSM_SRC_REPO:-https://github.com/prysmaticlabs/prysm}
    - DOCKER_TAG=${PRYSM_DOCKER_TAG:-stable}
    - DOCKER_VC_TAG=${PRYSM_DOCKER_VC_TAG:-stable}
    - DOCKER_REPO=${PRYSM_DOCKER_REPO:-gcr.io/prysmaticlabs/prysm/beacon-chain}
    - DOCKER_VC_REPO=${PRYSM_DOCKER_VC_REPO:-gcr.io/prysmaticlabs/prysm/validator}

services:
  consensus:
    restart: "unless-stopped"
    build:
      target: consensus
      <<: *prysm-build
    image: prysm-consensus:local
    user: prysmconsensus
    stop_grace_period: 1m
    volumes:
      - prysmconsensus-data:/var/lib/prysm
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/prysm/ee-secret
    environment:
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}${PRYSM_PORT}:${PRYSM_PORT}/tcp
      - ${HOST_IP:-}${PRYSM_UDP_PORT}:${PRYSM_UDP_PORT}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${NETWORK}-consensus
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - ${CL_REST_PORT:-5052}
      # Allow larger messages so credential change messages can be sent
      - --rpc-max-page-size
      - "200000"
      - --grpc-max-msg-size
      - "268435456"
      - --execution-endpoint
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/prysm/ee-secret/jwtsecret
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --p2p-max-peers
      - ${CL_MAX_PEER_COUNT:-70}
      - --verbosity
      - ${LOG_LEVEL}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --monitoring-port
      - "8008"
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
      - --enable-debug-rpc-endpoints
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus

volumes:
  prysmconsensus-data:
  jwtsecret:
