# Send client stats to beaconcha.in service
version: "3.9"
services:
  consensus:
    command:
      - --monitoring-host
      - 0.0.0.0
  validator:
    command:
      - --monitoring-host
      - 0.0.0.0
  client-stats:
    image: prysm-consensus:local
    volumes:
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - client-stats
      - --validator-metrics-url
      - http://validator:8081/metrics
      - --beacon-node-metrics-url
      - http://consensus:8080/metrics
      - --clientstats-api-url
      - https://beaconcha.in/api/v1/client/metrics?apikey=${BEACON_STATS_API}&machine=${BEACON_STATS_MACHINE}
