version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./reth
      dockerfile: ${RETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${RETH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${RETH_DOCKER_TAG}
    stop_grace_period: 5m
    stop_signal: SIGINT
    image: reth:local
    user: reth
    environment:
      - JWT_SECRET=${JWT_SECRET:-}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - reth-el-data:/var/lib/reth
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/reth/ee-secret
    ports:
      - ${HOST_IP:-0.0.0.0}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-0.0.0.0}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - reth
      - node
      - --db
      - /var/lib/reth
      - --chain
      - ${NETWORK}
      - --metrics
      - 0.0.0.0:6060
      - --config
      - /var/lib/reth/reth.toml
      - --port
      - ${EL_P2P_PORT:-30303}
      - --discovery.port
      - ${EL_P2P_PORT:-30303}
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${EL_RPC_PORT:-8545}
      - --http.api
      - web3,eth,net
      - --http.corsdomain=*
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EL_WS_PORT:-8546}
      - --ws.api
      - web3,eth,net
      - --ws.origins=*
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.jwtsecret
      - /var/lib/reth/ee-secret/jwtsecret
volumes:
  reth-el-data:
  jwtsecret:
