x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./reth
      dockerfile: ${RETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${RETH_SRC_BUILD_TARGET:-main}
        - SRC_REPO=${RETH_SRC_REPO:-https://github.com/paradigmxyz/reth}
        - DOCKER_TAG=${RETH_DOCKER_TAG:-latest}
        - DOCKER_REPO=${RETH_DOCKER_REPO:-ghcr.io/paradigmxyz/reth}
    stop_grace_period: 5m
    stop_signal: SIGINT
    image: reth:local
    pull_policy: never
    user: reth
    environment:
      - JWT_SECRET=${JWT_SECRET:-}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ARCHIVE_NODE=${EL_ARCHIVE_NODE:-}
      - NETWORK=${NETWORK}
      - STATIC_DIR=${ANCIENT_DIR}
      # Make this RUST_LOG=${LOG_LEVEL:-info},engine=trace when requiring deep debug
      # RPC debug can be done with jsonrpsee=trace or jsonrpsee::target=trace for a specific target
      - RUST_LOG=${LOG_LEVEL:-info}
      - RUST_LOG_STYLE=never
    volumes:
      - reth-el-data:/var/lib/reth
      - ${ANCIENT_DIR:-.nada}:/var/lib/static
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/reth/ee-secret
    ports:
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
      - ${HOST_IP:-}:${EL_P2P_PORT_2:-30304}:${EL_P2P_PORT_2:-30304}/udp
    networks:
      default:
        aliases:
          - eth1
          - ${EL_ALIAS:-default-execution}  # This allows multiple Eth Docker stacks all connected to the same bridge network
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - reth
      - node
      - --datadir
      - /var/lib/reth
      - --metrics
      - 0.0.0.0:6060
      - --port
      - ${EL_P2P_PORT:-30303}
      - --discovery.port
      - ${EL_P2P_PORT:-30303}
      - --enable-discv5-discovery
      - --discovery.v5.port
      - ${EL_P2P_PORT_2:-30304}
      - --nat
      - publicip
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${EL_RPC_PORT:-8545}
      - --http.corsdomain=*
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EL_WS_PORT:-8546}
      - --ws.origins=*
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.jwtsecret
      - /var/lib/reth/ee-secret/jwtsecret
      - --max-outbound-peers
      - ${EL_MAX_PEER_COUNT:-100}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=6060
      - metrics.instance=execution
      - metrics.network=${NETWORK}

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    user: "10001:10001"
    restart: "no"
    volumes:
      - reth-el-data:/var/lib/reth
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  reth-el-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
