# Sigma Prime Siren, for use with Lighthouse
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  siren:
    restart: "unless-stopped"
    image: ${SIREN_DOCKER_REPO}:${SIREN_DOCKER_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.$(SIREN_HOST:-siren}.service=${SIREN_HOST:-siren}
      - traefik.http.routers.${SIREN_HOST:-siren}.entrypoints=websecure
      - traefik.http.routers.${SIREN_HOST:-siren}.rule=Host(`${SIREN_HOST:-siren}.${DOMAIN}`)
      - traefik.http.routers.${SIREN_HOST:-siren}.tls.certresolver=letsencrypt
      - traefik.http.services.${SIREN_HOST:-siren}.loadbalancer.server.port=80
