version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "unless-stopped"
    build:
      context: ./teku
      args:
        - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${TEKU_DOCKER_TAG}
      dockerfile: ${TEKU_DOCKERFILE}
    image: teku:local
    user: teku
    stop_grace_period: 1m
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/teku/ee-secret
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g -Xmx4g
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
      - MEV_BOOST=${MEV_BOOST}
    ports:
      - ${HOST_IP:-0.0.0.0}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-0.0.0.0}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /opt/teku/bin/teku
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=${NETWORK}
      - --ee-endpoint=${EL_NODE}
      - --ee-jwt-secret-file
      - /var/lib/teku/ee-secret/jwtsecret
      - --p2p-port=${CL_P2P_PORT:-9000}
      - --p2p-peer-upper-bound=${CL_MAX_PEER_COUNT:-100}
      - --p2p-peer-lower-bound=${CL_MIN_PEER_COUNT:-64}
      - --validators-keystore-locking-enabled=true
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validators-graffiti=${GRAFFITI}
      - --logging=${LOG_LEVEL}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
      - --rest-api-interface=0.0.0.0
      - --rest-api-port=${CL_REST_PORT:-5052}
      - --metrics-enabled=true
      - --metrics-port=8008
      - --metrics-interface=0.0.0.0
      - --metrics-host-allowlist=*
      - --validator-api-enabled=true
      - --validator-api-port=${KEY_API_PORT:-7500}
      - --validator-api-host-allowlist=*
      - --validator-api-cors-origins=*
      - --validator-api-keystore-file=/var/lib/teku/teku-keyapi.keystore
      - --validator-api-keystore-password-file=/var/lib/teku/teku-keyapi.password
      - --validators-proposer-default-fee-recipient=${FEE_RECIPIENT}

  validator-import:
    profiles: ["tools"]
    restart: "no"
    image: teku:local
    user: root
    volumes:
      - teku-data:/var/lib/teku
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
    entrypoint: validator-import.sh

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /opt/teku/bin/teku
      - voluntary-exit
      - --beacon-node-api-endpoint=http://consensus:5052
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - teku-data:/var/lib/teku
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TLS="true"
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - consensus
    entrypoint:
      - keymanager.sh
      - /var/lib/teku/validator/key-manager/validator-api-bearer
      - consensus

volumes:
  teku-data:
  jwtsecret:
