x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

x-build: &teku-build
  context: ./teku
  dockerfile: ${TEKU_DOCKERFILE}
  args:
    - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
    - SRC_REPO=${TEKU_SRC_REPO:-https://github.com/ConsenSys/teku}
    - DOCKER_TAG=${TEKU_DOCKER_TAG:-latest}
    - DOCKER_REPO=${TEKU_DOCKER_REPO:-consensys/teku}

services:
  consensus:
    restart: "unless-stopped"
    build:
      <<: *teku-build
    image: teku:local
    pull_policy: never
    user: teku
    stop_grace_period: 1m
    volumes:
      - tekuconsensus-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/teku/ee-secret
    environment:
      - JAVA_OPTS=${TEKU_HEAP:--Xmx6g}
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MEV_BOOST=${MEV_BOOST}
      - MEV_NODE=${MEV_NODE}
      - BEACON_STATS_API=${BEACON_STATS_API}
      - BEACON_STATS_MACHINE=${BEACON_STATS_MACHINE}
      - CL_EXTRAS=${CL_EXTRAS:-}
      - VC_EXTRAS=
      - DOPPELGANGER=false
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=true
      - WEB3SIGNER=false
      - EMBEDDED_VC=false
      - NETWORK=${NETWORK}
    ports:
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
          - ${NETWORK}-consensus
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /opt/teku/bin/teku
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --ee-endpoint=${EL_NODE}
      - --ee-jwt-secret-file
      - /var/lib/teku/ee-secret/jwtsecret
      - --eth1-deposit-contract-max-request-size=1000
      - --p2p-port=${CL_P2P_PORT:-9000}
      - --p2p-peer-upper-bound=${CL_MAX_PEER_COUNT:-100}
      - --p2p-peer-lower-bound=${CL_MIN_PEER_COUNT:-64}
      - --logging=${LOG_LEVEL}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
      - --rest-api-interface=0.0.0.0
      - --rest-api-port=${CL_REST_PORT:-5052}
      - --beacon-liveness-tracking-enabled=true
      - --metrics-enabled=true
      - --metrics-port=8008
      - --metrics-interface=0.0.0.0
      - --metrics-host-allowlist=*
      - --validators-proposer-default-fee-recipient=${FEE_RECIPIENT}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8008
      - metrics.instance=consensus

volumes:
  tekuconsensus-data:
  jwtsecret:

networks:
  default:
    enable_ipv6: ${IPV6:-false}
