version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  validator:
    restart: "unless-stopped"
    build:
      context: ./teku
      args:
        - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${TEKU_DOCKER_TAG}
      dockerfile: ${TEKU_DOCKERFILE}
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=${TEKU_HEAP:--XX:SoftMaxHeapSize=2g -Xmx5g}
      - MEV_BOOST=${MEV_BOOST}
      - VC_EXTRAS=${VC_EXTRAS:-}
      - DOPPELGANGER=${DOPPELGANGER:-}
      - GRAFFITI=${GRAFFITI:-}
      - DEFAULT_GRAFFITI=${DEFAULT_GRAFFITI:-false}
    <<: *logging
    entrypoint:
      - docker-entrypoint-vc.sh
      - /opt/teku/bin/teku
      - validator-client
      - --beacon-node-api-endpoints=${CL_NODE:-http://consensus:5052}
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=auto
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validators-early-attestations-enabled=false
      - --validator-api-enabled=true
      - --validator-api-interface=0.0.0.0
      - --validator-api-port=${KEY_API_PORT:-7500}
      - --validator-api-host-allowlist=*
      - --validator-api-cors-origins=*
      - --validator-api-keystore-file=/var/lib/teku/teku-keyapi.keystore
      - --validator-api-keystore-password-file=/var/lib/teku/teku-keyapi.password
      - --validators-proposer-default-fee-recipient=${FEE_RECIPIENT}
      - --validators-keystore-locking-enabled=false

  validator-exit:
    profiles: ["tools"]
    restart: "no"
    image: teku:local
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /opt/teku/bin/teku
      - voluntary-exit
      - --beacon-node-api-endpoint=${CL_NODE:-http://consensus:5052}
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validator-keys=/var/lib/teku/validator/key-manager/local:/var/lib/teku/validator/key-manager/local-passwords

  validator-keys:
    profiles: ["tools"]
    restart: "no"
    build:
      context: ./vc-utils
    image: vc-utils:local
    user: root
    volumes:
      - teku-data:/var/lib/teku
      - ./.eth/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TLS="true"
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
      - KEY_API_PORT=${KEY_API_PORT:-7500}
    depends_on:
      - validator
    entrypoint:
      - keymanager.sh
      - /var/lib/teku/validator/key-manager/validator-api-bearer
      - validator

volumes:
  teku-data:
