version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./teku
      args:
        - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${TEKU_DOCKER_TAG}
      dockerfile: ${TEKU_DOCKERFILE}
    image: teku:merge
    user: teku
    stop_grace_period: 1m
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/teku/secrets
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g -Xmx4g
      - RAPID_SYNC_URL=${RAPID_SYNC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OVERRIDE_TTD=${OVERRIDE_TTD}
    ports:
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - /opt/teku/bin/teku
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=${NETWORK}
      - --ee-endpoint=${EL_NODE}
      - --ee-jwt-secret-file
      - /var/lib/teku/secrets/jwtsecret
      - --p2p-port=${CL_P2P_PORT:-9000}
      - --p2p-peer-upper-bound=${TEKU_PEER_COUNT}
      - --validators-keystore-locking-enabled=true
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validators-graffiti=${GRAFFITI}
      - --logging=${LOG_LEVEL}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
      - --rest-api-interface=0.0.0.0
      - --rest-api-port=5052
      - --metrics-enabled=true
      - --metrics-port=8008
      - --metrics-interface=0.0.0.0
      - --metrics-host-allowlist=*
      - --validator-api-enabled=true
      - --validator-api-port=${KEY_API_PORT:-7500}
      - --validator-api-host-allowlist=*
      - --validator-api-cors-origins=*
      - --validator-api-keystore-file=/var/lib/teku/teku-keyapi.keystore
      - --validator-api-keystore-password-file=/var/lib/teku/teku-keyapi.password
      - --validators-proposer-default-fee-recipient=${REWARDS_TO}
  get-keyapi-token:
    restart: "no"
    image: alpine:latest
    user: "10002"
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cat var/lib/teku/validator/key-manager/validator-api-bearer
        echo
  validator-import:
    restart: "no"
    image: teku:merge
    user: root
    volumes:
      - teku-data:/var/lib/teku
      - ${DEPCLI_LOCALDIR}/validator_keys:/validator_keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD:-}
    entrypoint: validator-import.sh
  validator-exit:
    restart: "no"
    image: teku:merge
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /opt/teku/bin/teku
      - voluntary-exit
      - --beacon-node-api-endpoint=http://consensus:5052
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
  validator-list:
    restart: "no"
    image: teku:merge
    user: teku
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        for file in /var/lib/teku/validator-keys/*; do
          echo -n "0x"
          cat $${file} | jq -r .pubkey
        done
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  teku-data:
  jwtsecret:
