# EthPandaOps Xatu, for use alongside a consensus layer client
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  xatu:
    restart: "unless-stopped"
    image: ${XATU_DOCKER_REPO}:${XATU_DOCKER_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --preset
      - ethpandaops
      - --beacon-node-url=${CL_NODE}
      - --output-authorization=${XATU_KEY}
