ARG DOCKER_TAG

FROM hyperledger/besu:${DOCKER_TAG}

#Next two are unused but included to avoid warnings
ARG BUILD_TARGET
ARG USER

ARG UID

USER root

RUN usermod -u "${UID}" besu

# Create data mount point with permissions
RUN mkdir -p /var/lib/besu && chown -R besu:besu /var/lib/besu && chmod -R 700 /var/lib/besu

# Use an unprivileged user.
USER besu

ENTRYPOINT /opt/besu/bin/besu
