# This file is not intended to be modified - any changes here could be overwritten next time you update.
# If you just need to add some new scrape targets to Prometheus, place these in the conf.d folder.
# You can use the existing files as inspiration, and the docs are here:
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#
# If you need to override the settings in this file, or add other top-level configuration
# (e.g.) remote_write config, please use custom-prom.yml.
# The modifications in that file will supercede the settings here (or extend, in the case of lists)

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:      12s # Timeout must be shorter than the interval
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Service detection from the Docker socket.
#
# If you have extra containers you'd like to monitor, you will need to add the following labels:
#   - `metrics.scrape=true`
#   - `metrics.port=<the metrics port>`
# And you will have to ensure that the container is connected to the same network by including
# `ext-network.yml` in your .env file.
scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
        - source_labels: [__meta_docker_container_label_metrics_scrape]
          regex: true
          action: keep
        - source_labels: [__meta_docker_container_label_com_docker_compose_service]
          target_label: job
        - source_labels: [__meta_docker_container_label_com_docker_compose_project]
          target_label: project
        - action: replace  # Optional: override metrics_path using metrics.path (default is /metrics)
          regex: (.+)
          source_labels:
          - __meta_docker_container_label_metrics_path
          target_label: __metrics_path__
        - action: replace  # Required: Configure the HTTP host and port to scrape using metrics.port
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_docker_container_label_metrics_port
          target_label: __address__
        - action: replace  # Optional: Sets Prometheus 'job' label using metrics.job, otherwise uses the compose service name
          regex: (.+)
          source_labels:
          - __meta_docker_container_label_metrics_job
          target_label: job
        - action: replace  # Optional: override the global scrape interval using metrics.interval
          regex: (.+)
          source_labels:
          - __meta_docker_container_label_metrics_interval
          target_label: __scrape_interval__
        - action: replace  # Optional: Sets Prometheus 'instance' label using metrics.instance, otherwise uses IP:PORT
          regex: (.+)
          source_labels:
          - __meta_docker_container_label_metrics_instance
          target_label: instance

scrape_config_files:
  - /etc/prometheus/conf.d/*.yml
