remote_write:
  - url: https://vm.monitoring.gcp.obol.tech/write
    authorization:
      credentials: OBOL_PROM_REMOTE_WRITE_TOKEN
    write_relabel_configs:
      - source_labels: [job]
        regex: "charon"
        action: keep # Keeps charon metrics and drop metrics from other containers.