  - job_name: ssv
    metrics_path: /metrics
    static_configs:
      - targets:
        - ssv-node:15000
  - job_name: ssv_health
    metrics_path: /health
    static_configs:
      - targets:
        - ssv-node:15000
