# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: P8E80F9AEF21F6940
    url: http://loki:3100
    editable: true
