{
 "title": "node-exporter_dashboard",
 "description": "Alerts for Linux Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [ "alerts" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Current Status", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 } },
  { "title": "Historic Log", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 } }
 ]
}