ARG DOCKER_TAG
FROM flashbots/mev-boost:${DOCKER_TAG} as mev

# Unused, this is here to avoid build time complaints
ARG BUILD_TARGET

ARG USER=mev
ARG UID=10666

# See https://stackoverflow.com/a/55757473/12429735RUN
RUN adduser \
    --disabled-password \
    --gecos "" \
    --shell "/sbin/nologin" \
    --uid "${UID}" \
    "${USER}"

USER ${USER}
