ARG DOCKER_TAG
ARG DOCKER_REPO
FROM ${DOCKER_REPO}:${DOCKER_TAG}

ARG USER=mev
ARG UID=10666

# See https://stackoverflow.com/a/55757473/12429735RUN
RUN adduser \
    --disabled-password \
    --gecos "" \
    --shell "/sbin/nologin" \
    --uid "${UID}" \
    "${USER}"

USER ${USER}
