ARG DOCKER_TAG
FROM flashbots/mev-boost:${DOCKER_TAG} as mev

# Unused, this is here to avoid build time complaints
ARG BUILD_TARGET

FROM debian:bullseye-slim

RUN mkdir -p /app
COPY --from=mev /app/ /app

ENTRYPOINT ["/app/mev-boost"]
