# Scrape Coingeck price feeds

scrape_configs:
  - job_name: 'json'
    metrics_path: /probe
    scrape_interval: 300s
    params:
      module: [default]
    static_configs:
    - targets:
      - https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: json-exporter:7979
