name: Source build Nimbus Fluffy

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "42 7 * * 2"  # Weekly Tuesday at 7:42 AM UTC
  workflow_dispatch:

jobs:
  build-nimbus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Nimbus/Nimbus/Fluffy
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=nimbus.yml:nimbus-el.yml:fluffy.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
          FLUFFY_DOCKERFILE=Dockerfile.source
          var=FLUFFY_DOCKERFILE
          set_value_in_env
          NETWORK=mainnet
          var=NETWORK
          set_value_in_env
          PORTAL=true
          var=PORTAL
          set_value_in_env
          EL_MINIMAL_NODE=true
          var=EL_MINIMAL_NODE
          set_value_in_env
      - name: Build clients
        run: ./ethd update --non-interactive
      - name: Test Nimbus Fluffy
        run: ./.github/check-service.sh portal
