name: Source build Nimbus EL

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "42 7 * * 2"  # Weekly Tuesday at 7:42 AM UTC
  workflow_dispatch:

jobs:
  build-nimbus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Nimbus/Nimbus
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=nimbus.yml:nimbus-el.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
          NIMEL_DOCKERFILE=Dockerfile.source
          var=NIMEL_DOCKERFILE
          set_value_in_env
      - name: Build clients
        run: ./ethd update
      - name: Test the stack
        uses: ./.github/actions/test_client_stack
      - name: Set Nimbus/Nimbus w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=nimbus-cl-only.yml:nimbus-vc-only.yml:nimbus-el.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Test the stack
        uses: ./.github/actions/test_client_stack
