name: Source build ethstaker-deposit-cli

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "42 7 * * 2"  # Weekly Tuesday at 7:42 AM UTC
  workflow_dispatch:

jobs:
  build-deposit-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set ethstaker-deposit-cli
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=deposit-cli.yml
          var=COMPOSE_FILE
          set_value_in_env
          DEPCLI_DOCKERFILE=Dockerfile.source
          var=DEPCLI_DOCKERFILE
          set_value_in_env
      - name: Build clients
        run: ./ethd update --non-interactive
