name: docker-compose-actions-workflow

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint sources
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Test ethd
        run: |
          cp default.env .env
          ./ethd up
