name: Test Teku and Besu
run-name: Test Teku and Besu

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-teku-besu:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-teku') ||
      contains(github.event.pull_request.labels.*.name, 'test-besu') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Teku/Besu
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku
        run: |
          ./.github/check-service.sh consensus
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
      - name: Set Teku/Besu w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku-cl-only.yml:teku-vc-only.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Teku VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
