name: docker-compose-actions-workflow

on:
  pull_request:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test-teku-besu:
    if: |
      github.event.issue.pull_request && (
      contains(github.event.comment.body, '/test-teku')||
      contains(github.event.comment.body, '/test-besu')||
      contains(github.event.comment.body, '/test-all') )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ouzi-dev/commit-status-updater@v2
      - if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          status: "${{ job.status }}"
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Teku/Besu
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku
        run: |
          ./.github/check-service.sh consensus
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
      - name: Set Teku/Besu w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku-cl-only.yml:teku-vc-only.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Teku VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
