name: Test Grandine and Nimbus EL

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-grandine-nimbus:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-grandine') ||
      contains(github.event.pull_request.labels.*.name, 'test-nimbus-el') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Grandine/Nimbus EL
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=grandine-allin1.yml:nimbus-el.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
      - name: Start Grandine/Nimbus EL
        run: ./ethd up
      - name: Pause for 30 seconds
        run: sleep 30
      - name: Test Nimbus EL
        run: ./.github/check-service.sh execution
      - name: Test Grandine CL
        run: ./.github/check-service.sh consensus
#      - name: Test Grandine VC
#        run: ./.github/check-service.sh validator
      - name: Set Grandine/Nimbus EL w/ Lighthouse VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=grandine-cl-only.yml:lighthouse-vc-only.yml:nimbus-el.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Test the stack
        uses: ./.github/actions/test_client_stack
