name: Test Prysm and Geth

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-prysm-geth:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-prysm') ||
      contains(github.event.pull_request.labels.*.name, 'test-geth') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Prysm/Geth
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=prysm.yml:geth.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
          CL_NODE=consensus:4000
          var=CL_NODE
          set_value_in_env
      - name: Test the stack
        uses: ./.github/actions/test_client_stack
      - name: Set Prysm/Geth w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=prysm-cl-only.yml:prysm-vc-only.yml:geth.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Test the stack
        uses: ./.github/actions/test_client_stack
