name: Test Lodestar and Erigon
run-name: Test Lodestar and Erigon

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test-lodestar-erigon:
    if: |
      github.event.issue.pull_request && (
      contains(github.event.comment.body, '/test-lodestar')||
      contains(github.event.comment.body, '/test-erigon')||
      contains(github.event.comment.body, '/test-all') )
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Test Lodestar and Erigon
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Lodestar/Erigon
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lodestar.yml:erigon.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lodestar/Erigon
        run: |
          ./ethd up
      - name: Test Lodestar CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Lodestar VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Geth
        run: |
          ./.github/check-service.sh execution
      - name: Set Lodestar/Erigon w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lodestar-cl-only.yml:lodestar-vc-only.yml:erigon.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lodestar/Erigon
        run: |
          ./ethd up
      - name: Test Lodestar CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Lodestar VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Erigon
        run: |
          ./.github/check-service.sh execution
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Test Lodestar and Erigon
