name: Test ethd update

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Test ethd update for missed variables
        run: ./ethd update --debug --non-interactive
