name: Test Lodestar and Erigon
run-name: Test Lodestar and Erigon

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-lodestar-erigon:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-lodestar') ||
      contains(github.event.pull_request.labels.*.name, 'test-erigon') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Lodestar/Erigon
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lodestar.yml:erigon.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lodestar/Erigon
        run: |
          ./ethd up
      - name: Test Lodestar CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Lodestar VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Geth
        run: |
          ./.github/check-service.sh execution
      - name: Set Lodestar/Erigon w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lodestar-cl-only.yml:lodestar-vc-only.yml:erigon.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lodestar/Erigon
        run: |
          ./ethd up
      - name: Test Lodestar CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Lodestar VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Erigon
        run: |
          ./.github/check-service.sh execution
