name: Test Lighthouse and Geth
run-name: Test Lighthouse and Geth

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-lighthouse-geth:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-lighthouse') ||
      contains(github.event.pull_request.labels.*.name, 'test-reth') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Lighthouse/Geth
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lighthouse.yml:geth.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lighthouse/Geth
        run: |
          ./ethd up
      - name: Test Lighthouse CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Lighthouse VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Geth
        run: |
          ./.github/check-service.sh execution
      - name: Set Lighthouse/Geth w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lighthouse-cl-only.yml:lighthouse-vc-only.yml:geth.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lighthouse/Geth
        run: |
          ./ethd up
      - name: Test Lighthouse CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Lighthouse VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Geth
        run: |
          ./.github/check-service.sh execution
