name: Test Nimbus and Nethermind
run-name: Test Nimbus and Nethermind

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test-nimbus-nethermind:
    if: |
      github.event.issue.pull_request && (
      contains(github.event.comment.body, '/test-nimbus')||
      contains(github.event.comment.body, '/test-nethermind')||
      contains(github.event.comment.body, '/test-all') )
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Test Nimbus and Nethermind
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Nimbus/Nethermind
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=nimbus.yml:nethermind.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Nimbus/Nethermind
        run: |
          ./ethd up
      - name: Test Nimbus
        run: |
          ./.github/check-service.sh consensus
      - name: Test Nethermind
        run: |
          ./.github/check-service.sh execution
      - name: Set Nimbus/Nethermind w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=nimbus-cl-only.yml:nimbus-vc-only.yml:nethermind.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Nimbus/Nethermind
        run: |
          ./ethd up
      - name: Test Nimbus CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Nimbus VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Nethermind
        run: |
          ./.github/check-service.sh execution
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Test Nimbus and Nethermind
