name: Test Grandine and Nimbus EL w/ Fluffy Portal

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-grandine-nimbus-fluffy:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-fluffy') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Grandine/Nimbus EL w/ Fluffy
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=grandine-allin1.yml:nimbus-el.yml:fluffy.yml
          var=COMPOSE_FILE
          set_value_in_env
          NETWORK=mainnet
          var=NETWORK
          set_value_in_env
          PORTAL=true
          var=PORTAL
          set_value_in_env
          EL_MINIMAL_NODE=true
          var=EL_MINIMAL_NODE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
      - name: Start Grandine/Nimbus EL w/ Fluffy
        run: ./ethd up
      - name: Pause for 30 seconds
        run: sleep 30
      - name: Test Nimbus EL
        run: ./.github/check-service.sh execution
      - name: Test Nimbus Fluffy
        run: ./.github/check-service.sh portal
