name: Test Teku and Besu
run-name: Test Teku and Besu

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test-teku-besu:
    if: |
      github.event.issue.pull_request && (
      contains(github.event.comment.body, '/test-teku')||
      contains(github.event.comment.body, '/test-besu')||
      contains(github.event.comment.body, '/test-all') )
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Test Teku and Besu
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Create .env file
        run: |
          cp default.env .env
      - name: Set Teku/Besu
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku
        run: |
          ./.github/check-service.sh consensus
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
      - name: Set Teku/Besu w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=teku-cl-only.yml:teku-vc-only.yml:besu.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Teku/Besu
        run: |
          ./ethd up
      - name: Test Teku CL
        run: |
          ./.github/check-service.sh consensus
      - name: Test Teku VC
        run: |
          ./.github/check-service.sh validator
      - name: Test Besu
        run: |
          ./.github/check-service.sh execution
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Test Teku and Besu
