name: Test Lighthouse and Reth
run-name: Test Lighthouse and Reth

on:
  push:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches: [main]

jobs:
  test-lighthouse-reth:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-lighthouse') ||
      contains(github.event.pull_request.labels.*.name, 'test-reth') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: cp default.env .env
      - name: Set Lighthouse/Reth
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lighthouse.yml:reth.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
      - name: Start Lighthouse/Reth
        run: ./ethd up
      - name: Pause for 30 seconds
        run: sleep 30
      - name: Test Reth
        run: ./.github/check-service.sh execution
      - name: Test Lighthouse CL
        run: ./.github/check-service.sh consensus
      - name: Test Lighthouse VC
        run: ./.github/check-service.sh validator
      - name: Set Lighthouse/Reth w/ VC
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lighthouse-cl-only.yml:lighthouse-vc-only.yml:reth.yml
          var=COMPOSE_FILE
          set_value_in_env
      - name: Start Lighthouse/Reth
        run: ./ethd up
      - name: Pause for 30 seconds
        run: sleep 30
      - name: Test Reth
        run: ./.github/check-service.sh execution
      - name: Test Lighthouse CL
        run: ./.github/check-service.sh consensus
      - name: Test Lighthouse VC
        run: ./.github/check-service.sh validator
