ARG DOCKER_TAG
FROM prysmaticlabs/prysm-beacon-chain:${DOCKER_TAG} as bnsource

FROM debian:buster-slim as beacon

#Included here to avoid build-time complaints
ARG BUILD_TARGET

ARG USER
ARG UID

# See https://stackoverflow.com/a/55757473/12429735RUN
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/bin/false" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

# Create data mount point with permissions
RUN mkdir -p /var/lib/prysm && chown ${USER}:${USER} /var/lib/prysm && chmod 700 /var/lib/prysm

COPY --from=bnsource /app/beacon-chain/image.binary /usr/local/bin/beacon-chain

# Use an unprivileged user.
USER ${USER}:${USER}

#EXPOSE 4000 13000 12000/udp
ENTRYPOINT ["beacon-chain", "--datadir", "/var/lib/prysm", "--http-web3provider", "http://geth:8545", "--rpc-host", "0.0.0.0"]

FROM prysmaticlabs/prysm-validator:${DOCKER_TAG} as vcsource

FROM debian:buster-slim as validator

ARG USER
ARG UID

# See https://stackoverflow.com/a/55757473/12429735RUN
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/bin/false" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

# Create data mount point with permissions
RUN mkdir -p /var/lib/prysm && chown ${USER}:${USER} /var/lib/prysm && chmod 700 /var/lib/prysm

COPY --from=vcsource /app/validator/image.binary /usr/local/bin/validator
COPY ./create-prysm-validator-wallet.sh /usr/local/bin

# Use an unprivileged user.
USER ${USER}:${USER}

FROM prysmaticlabs/prysm-slasher:${DOCKER_TAG} as slsource

FROM debian:buster-slim as slasher

ARG USER
ARG UID

# See https://stackoverflow.com/a/55757473/12429735RUN
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/bin/false" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

# Create data mount point with permissions
RUN mkdir -p /var/lib/prysm && chown ${USER}:${USER} /var/lib/prysm && chmod 700 /var/lib/prysm

COPY --from=slsource /app/slasher/image.binary /usr/local/bin/slasher

# Use an unprivileged user.
USER ${USER}:${USER}
